var KOK = (typeof window !== 'undefined') ? window : global;

KOK.ENV_BECERI = {
  kod: 'BECERI',
  ad: 'Mesleki Beceri Envanteri',
  olcek: ['Hiç yapamam','Zorlanırım','Orta düzeyde yaparım','İyi yaparım','Çok iyi yaparım'],
  boyutlar: [
    { k:'SAY', ad:'Sayısal ve analitik beceri',
      aciklama:'Sayılarla çalışmayı, veriyi okumayı ve bir problemi adımlara bölerek çözmeyi kapsar. Hesap yapmanın yanında sonucun ne anlama geldiğini yorumlamayı da içerir.',
      gelistirme:'Her gün bir haber grafiğine bakıp ne anlattığını iki cümleyle yaz.' },
    { k:'SOZ', ad:'Sözel ve iletişim becerisi',
      aciklama:'Yazılı ve sözlü anlatımı, dinlemeyi ve karşıdakine uygun dille aktarmayı kapsar. Bir fikri kendi cümlelerinle kurup başkasına geçirebilmek temelidir.',
      gelistirme:'Okuduğun her metnin sonunda üç cümlelik özetini sesli olarak anlat.' },
    { k:'TEK', ad:'Teknik ve uygulamalı beceri',
      aciklama:'El becerisi gerektiren işleri, alet kullanmayı ve bir düzeneği kurup onarmayı kapsar. Bir şeyin nasıl çalıştığını anlamak için parçalara ayırıp yeniden birleştirmeyi içerir.',
      gelistirme:'Evde bozulan küçük bir eşyayı atmadan önce vidalarını açıp içine bakarak incele.' },
    { k:'TAS', ad:'Görsel ve tasarım becerisi',
      aciklama:'Görsel düzen kurmayı, renk ve biçim seçmeyi, bir fikri resme dökmeyi kapsar. Bir işin hem işe yaraması hem de bakana düzenli görünmesiyle ilgilenir.',
      gelistirme:'Beğendiğin bir afişi elle yeniden çizerek yazı ve boşluk düzenini taklit et.' },
    { k:'LID', ad:'Liderlik ve organizasyon becerisi',
      aciklama:'Bir grubu ortak hedefe yöneltmeyi, işi bölmeyi ve süreci takip etmeyi kapsar. Anlaşmazlıkta ortak zemin bulmak da bu becerinin parçasıdır.',
      gelistirme:'Bir sonraki grup ödevinde görev dağılımını yapmayı üstlen ve listeyi herkesle paylaş.' },
    { k:'DIJ', ad:'Dijital beceri',
      aciklama:'Bilgisayarı ve telefonu bir şey üretmek için kullanmayı, bilgiyi doğrulamayı ve yeni araçları öğrenmeyi kapsar. Tanımadığı bir programı kurcalayarak çözebilme alışkanlığını içerir.',
      gelistirme:'Tablo programında kendi ders notlarını girip ortalamanı formülle hesaplayan bir dosya kur.' }
  ],
  maddeler: [
    { n:1,  m:'Alışverişte indirim sonrası ödeyeceğim tutarı kafamdan hesaplamak.', b:'SAY', t:false },
    { n:2,  m:'Okuduğum bir metni kendi cümlelerimle birkaç satırda özetlemek.', b:'SOZ', t:false },
    { n:3,  m:'Bir parçanın ölçüsünü alıp kesim yerini doğru işaretlemek.', b:'TEK', t:false },
    { n:4,  m:'Bir sunum slaydındaki yazıları okunur bir düzene sokmak.', b:'TAS', t:false },
    { n:5,  m:'Grup ödevinde kimin ne yapacağını yazıya dökmek.', b:'LID', t:false },
    { n:6,  m:'Telefonumdaki bir dosyayı bulup doğru kişiye göndermek.', b:'DIJ', t:false },
    { n:7,  m:'Anlatmak istediğim bir fikri basit bir çizimle göstermek.', b:'TAS', t:false },
    { n:8,  m:'Bir grafiğe bakıp hangi dönemde düşüş olduğunu söylemek.', b:'SAY', t:false },
    { n:9,  m:'Bir etkinliğin saat saat programını hazırlayıp takip etmek.', b:'LID', t:false },
    { n:10, m:'Bir dilekçeyi ya da resmi yazıyı kurallarına uygun yazmak.', b:'SOZ', t:false },
    { n:11, m:'Tablo programında bir sütunun toplamını formülle hesaplamak.', b:'DIJ', t:false },
    { n:12, m:'Yeni bir eşyayı kılavuzuna bakarak kurmak.', b:'TEK', t:false },
    { n:13, m:'Anlamadığım bir konuyu öğretmene net bir soruyla sormak.', b:'SOZ', t:false },
    { n:14, m:'İnternette bulduğum bir bilginin kaynağını kontrol etmek.', b:'DIJ', t:false },
    { n:15, m:'Günlük bir durumu çözmek için kendi denklemimi kurmak.', b:'SAY', t:false },
    { n:16, m:'Gevşeyen bir vidayı doğru aleti seçip sıkmak.', b:'TEK', t:false },
    { n:17, m:'Çektiğim bir fotoğrafı kırpıp daha dengeli bir kadraj yapmak.', b:'TAS', t:false },
    { n:18, m:'Tartışan iki arkadaşımı dinleyip ortak bir çözüm önermek.', b:'LID', t:false },
    { n:19, m:'Basit bir kod yazıp çalışmadığında hatasını bulmak.', b:'DIJ', t:false },
    { n:20, m:'Bir tasarımda birbirine uyan renkleri ve yazı tipini seçmek.', b:'TAS', t:false },
    { n:21, m:'Bir arkadaşımın sorununu kesmeden dinleyip anladığımı geri anlatmak.', b:'SOZ', t:false },
    { n:22, m:'Gönüllü bir projede görev dağıtıp herkesin ilerlemesini izlemek.', b:'LID', t:false },
    { n:23, m:'Uzun bir problemi küçük adımlara bölüp sırayla çözmek.', b:'SAY', t:false },
    { n:24, m:'Bir rafı parçalarından bakarak monte etmek.', b:'TEK', t:false },
    { n:25, m:'Grubumu temsil edip kararımızı öğretmene gerekçesiyle anlatmak.', b:'LID', t:false },
    { n:26, m:'İki farklı veri listesini karşılaştırıp aradaki farkın nedenini yorumlamak.', b:'SAY', t:false },
    { n:27, m:'Bilmediğim bir programı kurcalayarak ne işe yaradığını çözmek.', b:'DIJ', t:false },
    { n:28, m:'Bir etkinlik için sıfırdan afiş tasarlayıp öğeleri yerleştirmek.', b:'TAS', t:false },
    { n:29, m:'Çalışmayan bir aleti parça parça kontrol edip arızayı bulmak.', b:'TEK', t:false },
    { n:30, m:'Karşı görüşteki bir gruba örneklerle savunma konuşması yapmak.', b:'SOZ', t:false }
  ]
};
