var KOK = (typeof window !== 'undefined') ? window : global;

KOK.ENV_BOLUMLER = {

  bolumler: [

    {
      kod: 'TIP',
      ad: 'Tıp',
      grup: 'Sağlık bilimleri',
      puan: 'SAY',
      holland: 'ISR',
      yetenek: { SOZ:4, SAY:4, MAN:5, UZM:3, VER:5 },
      beceri:  { SAY:3, SOZ:4, TEK:4, TAS:1, LID:3, DIJ:3 },
      deger:   ['BAS','ILI'],
      kisilik: { S:5, DD:4, U:4 },
      isler:   'Hasta muayenesi, tanı koyma, tedavi yönetimi, ameliyat ve girişimler.',
      not:     'Altı yıllık eğitimin ardından uzmanlık için TUS gerekir, nöbet düzeni yaşam saatlerini belirler.'
    },
    {
      kod: 'DIS_HEKIMLIGI',
      ad: 'Diş Hekimliği',
      grup: 'Sağlık bilimleri',
      puan: 'SAY',
      holland: 'RIS',
      yetenek: { SOZ:3, SAY:3, MAN:4, UZM:5, VER:3 },
      beceri:  { SAY:2, SOZ:3, TEK:5, TAS:3, LID:2, DIJ:3 },
      deger:   ['BAG','BAS'],
      kisilik: { S:5, DD:4 },
      isler:   'Ağız ve diş muayenesi, dolgu ve kanal tedavisi, protez uygulaması, cerrahi çekim.',
      not:     'Gün küçük bir alanda el becerisiyle ve sabit duruşta geçer, bel ve boyun rahatsızlığı meslekte yaygındır.'
    },
    {
      kod: 'ECZACILIK',
      ad: 'Eczacılık',
      grup: 'Sağlık bilimleri',
      puan: 'SAY',
      holland: 'ICS',
      yetenek: { SOZ:4, SAY:4, MAN:4, UZM:2, VER:4 },
      beceri:  { SAY:4, SOZ:4, TEK:3, TAS:1, LID:3, DIJ:3 },
      deger:   ['GUV','ILI'],
      kisilik: { S:5, U:4 },
      isler:   'İlaç danışmanlığı, eczane işletmesi, ilaç üretimi, ruhsat ve kalite süreçleri.',
      not:     'Serbest eczane açmak sermaye ve nüfusa bağlı kota ister, mezunların bir bölümü ilaç firmalarında çalışır.'
    },
    {
      kod: 'HEMSIRELIK',
      ad: 'Hemşirelik',
      grup: 'Sağlık bilimleri',
      puan: 'SAY',
      holland: 'SIR',
      yetenek: { SOZ:4, SAY:3, MAN:4, UZM:2, VER:4 },
      beceri:  { SAY:3, SOZ:5, TEK:4, TAS:1, LID:3, DIJ:2 },
      deger:   ['ILI','GUV'],
      kisilik: { U:5, S:5, DD:5 },
      isler:   'Hasta bakımı, ilaç uygulaması, yoğun bakım takibi, hasta ve yakınını bilgilendirme.',
      not:     'Vardiya ve gece nöbeti kalıcıdır, istihdam geniş olsa da fiziksel yük yüksektir.'
    },
    {
      kod: 'FIZYOTERAPI',
      ad: 'Fizyoterapi ve Rehabilitasyon',
      grup: 'Sağlık bilimleri',
      puan: 'SAY',
      holland: 'SRI',
      yetenek: { SOZ:3, SAY:3, MAN:4, UZM:4, VER:3 },
      beceri:  { SAY:2, SOZ:4, TEK:5, TAS:1, LID:2, DIJ:2 },
      deger:   ['ILI','BAG'],
      kisilik: { U:4, S:4, DD:4 },
      isler:   'Hareket değerlendirmesi, egzersiz programı uygulama, manuel terapi, spor yaralanması rehabilitasyonu.',
      not:     'Ayakta ve bedensel güç isteyen bir iştir, aynı hastayla haftalarca süren tekrar gerektirir.'
    },
    {
      kod: 'BESLENME_DIYETETIK',
      ad: 'Beslenme ve Diyetetik',
      grup: 'Sağlık bilimleri',
      puan: 'SAY',
      holland: 'SIC',
      yetenek: { SOZ:4, SAY:4, MAN:3, UZM:1, VER:5 },
      beceri:  { SAY:4, SOZ:5, TEK:2, TAS:2, LID:2, DIJ:3 },
      deger:   ['ILI','BAG'],
      kisilik: { U:4, S:4 },
      isler:   'Beslenme durumu değerlendirme, diyet planlama, toplu beslenme hizmeti yönetimi, hasta takibi.',
      not:     'Hastane kadroları sınırlıdır, mezunların çoğu özel danışmanlıkta kendi hasta çevresini kurmak zorunda kalır.'
    },
    {
      kod: 'VETERINER',
      ad: 'Veteriner Hekimliği',
      grup: 'Sağlık bilimleri',
      puan: 'SAY',
      holland: 'IRS',
      yetenek: { SOZ:3, SAY:4, MAN:5, UZM:3, VER:4 },
      beceri:  { SAY:3, SOZ:3, TEK:5, TAS:1, LID:3, DIJ:2 },
      deger:   ['BAG','BAS'],
      kisilik: { DD:5, S:4 },
      isler:   'Hayvan muayenesi ve cerrahisi, sürü sağlığı yönetimi, gıda güvenliği denetimi, aşılama programları.',
      not:     'Eğitim beş yıl sürer, büyük hayvan pratiğinde saha koşulları ve yaralanma riski vardır.'
    },
    {
      kod: 'ODYOLOJI',
      ad: 'Odyoloji',
      grup: 'Sağlık bilimleri',
      puan: 'SAY',
      holland: 'ISR',
      yetenek: { SOZ:3, SAY:3, MAN:4, UZM:3, VER:5 },
      beceri:  { SAY:3, SOZ:4, TEK:5, TAS:1, LID:2, DIJ:4 },
      deger:   ['GUV','ILI'],
      kisilik: { S:5, U:4 },
      isler:   'İşitme testi uygulama, işitme cihazı uyumlandırma, denge değerlendirmesi, yenidoğan taraması.',
      not:     'Ölçüm cihazlarıyla çalışılan dar bir alandır, açılan kadro sayısı Hemşirelikten çok daha azdır.'
    },
    {
      kod: 'EBELIK',
      ad: 'Ebelik',
      grup: 'Sağlık bilimleri',
      puan: 'SAY',
      holland: 'SRC',
      yetenek: { SOZ:3, SAY:3, MAN:4, UZM:2, VER:4 },
      beceri:  { SAY:2, SOZ:5, TEK:4, TAS:1, LID:3, DIJ:2 },
      deger:   ['ILI','GUV'],
      kisilik: { DD:5, U:5, S:4 },
      isler:   'Gebelik takibi, doğum eylemi yönetimi, yenidoğan bakımı, aile planlaması danışmanlığı.',
      not:     'Doğumhane nöbeti ve saniyeler içinde karar gerektiren durumlar işin olağan parçasıdır.'
    },
    {
      kod: 'DIL_KONUSMA_TERAPISI',
      ad: 'Dil ve Konuşma Terapisi',
      grup: 'Sağlık bilimleri',
      puan: 'SAY',
      holland: 'SIA',
      yetenek: { SOZ:5, SAY:2, MAN:4, UZM:2, VER:4 },
      beceri:  { SAY:2, SOZ:5, TEK:3, TAS:2, LID:2, DIJ:3 },
      deger:   ['ILI','BAS'],
      kisilik: { U:5, S:4, DD:4 },
      isler:   'Konuşma bozukluğu değerlendirmesi, dil gelişimi terapisi, yutma güçlüğü tedavisi, işitme kaybı sonrası eğitim.',
      not:     'İlerleme aylarla ölçülür, aynı çalışmayı çocukla haftalarca tekrar etmek gerekir.'
    },

    {
      kod: 'BILGISAYAR_MUH',
      ad: 'Bilgisayar Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'IRC',
      yetenek: { SOZ:2, SAY:5, MAN:5, UZM:3, VER:4 },
      beceri:  { SAY:5, SOZ:2, TEK:4, TAS:2, LID:2, DIJ:5 },
      deger:   ['BAS','BAG'],
      kisilik: { A:4, S:4 },
      isler:   'Yazılım geliştirme, veri sistemleri, yapay zekâ, siber güvenlik.',
      not:     'Matematik ve soyut akıl yürütme ağırlıklıdır, öğrenmenin mezuniyetten sonra da sürmesi gerekir.'
    },
    {
      kod: 'ELEKTRIK_ELEKTRONIK_MUH',
      ad: 'Elektrik-Elektronik Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'RIC',
      yetenek: { SOZ:2, SAY:5, MAN:5, UZM:4, VER:4 },
      beceri:  { SAY:5, SOZ:2, TEK:5, TAS:2, LID:2, DIJ:4 },
      deger:   ['BAS','GUV'],
      kisilik: { S:4, A:4 },
      isler:   'Devre tasarımı, enerji sistemleri, gömülü yazılım, haberleşme altyapısı.',
      not:     'Fizik ve matematik yükü ilk iki yılda en ağır düzeydedir, bölümü uzatan öğrenci oranı yüksektir.'
    },
    {
      kod: 'MAKINE_MUH',
      ad: 'Makine Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'RIC',
      yetenek: { SOZ:2, SAY:5, MAN:4, UZM:5, VER:3 },
      beceri:  { SAY:5, SOZ:2, TEK:5, TAS:3, LID:3, DIJ:3 },
      deger:   ['BAS','GUV'],
      kisilik: { S:4, A:3 },
      isler:   'Makine ve parça tasarımı, üretim planlama, ısıtma soğutma sistemleri, bakım ve arıza analizi.',
      not:     'Her yıl çok sayıda mezun verir, işe fabrika sahasında vardiya düzeniyle başlamak yaygındır.'
    },
    {
      kod: 'INSAAT_MUH',
      ad: 'İnşaat Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'RCE',
      yetenek: { SOZ:2, SAY:5, MAN:4, UZM:5, VER:3 },
      beceri:  { SAY:5, SOZ:3, TEK:5, TAS:2, LID:4, DIJ:3 },
      deger:   ['BAS','BAG'],
      kisilik: { S:5, DD:4 },
      isler:   'Yapı statiği hesabı, şantiye yönetimi, altyapı projeleri, zemin ve malzeme denetimi.',
      not:     'İş sahada olduğu için şehir değiştirmek olağandır, sektör inşaat ekonomisiyle birlikte dalgalanır.'
    },
    {
      kod: 'ENDUSTRI_MUH',
      ad: 'Endüstri Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'EIC',
      yetenek: { SOZ:3, SAY:5, MAN:5, UZM:2, VER:5 },
      beceri:  { SAY:5, SOZ:4, TEK:2, TAS:2, LID:4, DIJ:4 },
      deger:   ['BAS','TAN'],
      kisilik: { D:4, S:4 },
      isler:   'Üretim ve süreç iyileştirme, tedarik zinciri planlama, kalite yönetimi, veri analitiği.',
      not:     'İş tanımı işletmeden işletmeye çok değişir, teknik derinlikten çok sistem kurma becerisi beklenir.'
    },
    {
      kod: 'YAZILIM_MUH',
      ad: 'Yazılım Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'ICR',
      yetenek: { SOZ:3, SAY:4, MAN:5, UZM:2, VER:4 },
      beceri:  { SAY:4, SOZ:3, TEK:4, TAS:2, LID:3, DIJ:5 },
      deger:   ['BAG','BAS'],
      kisilik: { S:5, A:4 },
      isler:   'Yazılım mimarisi, test ve kalite süreçleri, proje yönetimi, sistem bakımı.',
      not:     'Bilgisayar Mühendisliğine göre donanım ve teori daha az, süreç ve takım çalışması daha fazladır.'
    },
    {
      kod: 'BIYOMEDIKAL_MUH',
      ad: 'Biyomedikal Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'IRS',
      yetenek: { SOZ:3, SAY:5, MAN:5, UZM:4, VER:4 },
      beceri:  { SAY:5, SOZ:3, TEK:5, TAS:2, LID:2, DIJ:4 },
      deger:   ['BAS','ILI'],
      kisilik: { A:4, S:4 },
      isler:   'Tıbbi cihaz tasarımı, hastane teknik servisi, görüntüleme sistemleri, biyosinyal analizi.',
      not:     'Cihaz üretimi yurt içinde sınırlıdır, mezunların çoğu satış ve teknik servis tarafında iş bulur.'
    },
    {
      kod: 'HAVACILIK_UZAY_MUH',
      ad: 'Havacılık ve Uzay Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'IRC',
      yetenek: { SOZ:2, SAY:5, MAN:5, UZM:5, VER:4 },
      beceri:  { SAY:5, SOZ:2, TEK:4, TAS:3, LID:2, DIJ:4 },
      deger:   ['BAS','TAN'],
      kisilik: { S:5, A:4 },
      isler:   'Uçak ve insansız hava aracı tasarımı, aerodinamik analiz, uydu sistemleri, yapısal test.',
      not:     'İstihdam birkaç büyük savunma ve havacılık şirketine bağlıdır, işe girişte güvenlik soruşturması belirleyicidir.'
    },
    {
      kod: 'KIMYA_MUH',
      ad: 'Kimya Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'IRC',
      yetenek: { SOZ:2, SAY:5, MAN:5, UZM:3, VER:4 },
      beceri:  { SAY:5, SOZ:3, TEK:4, TAS:1, LID:3, DIJ:3 },
      deger:   ['BAS','GUV'],
      kisilik: { S:5, DD:4 },
      isler:   'Proses tasarımı, üretim tesisi işletme, kalite kontrol, arıtma ve geri kazanım.',
      not:     'Tesisler çoğunlukla şehir dışındadır, kimyasal maruziyet ve vardiya düzeni işin parçasıdır.'
    },
    {
      kod: 'GIDA_MUH',
      ad: 'Gıda Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'ICR',
      yetenek: { SOZ:3, SAY:4, MAN:4, UZM:2, VER:4 },
      beceri:  { SAY:4, SOZ:3, TEK:4, TAS:1, LID:3, DIJ:2 },
      deger:   ['GUV','BAS'],
      kisilik: { S:5, U:3 },
      isler:   'Üretim hattı denetimi, ürün geliştirme, hijyen ve kalite belgelendirme, raf ömrü çalışmaları.',
      not:     'Başlangıç ücretleri diğer mühendisliklerin altında kalır, üretim tesisinde vardiya yaygındır.'
    },
    {
      kod: 'CEVRE_MUH',
      ad: 'Çevre Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'IRS',
      yetenek: { SOZ:3, SAY:4, MAN:4, UZM:3, VER:5 },
      beceri:  { SAY:4, SOZ:4, TEK:4, TAS:1, LID:3, DIJ:3 },
      deger:   ['BAS','ILI'],
      kisilik: { U:4, S:4, A:3 },
      isler:   'Atık su arıtma tasarımı, hava kalitesi ölçümü, çevresel etki değerlendirmesi, atık yönetimi.',
      not:     'İşin büyük bölümü mevzuat ve rapor üzerinedir, kadro sayısı kamu bütçesiyle birlikte iner çıkar.'
    },
    {
      kod: 'HARITA_MUH',
      ad: 'Harita Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'RCI',
      yetenek: { SOZ:2, SAY:5, MAN:4, UZM:5, VER:5 },
      beceri:  { SAY:5, SOZ:2, TEK:5, TAS:2, LID:2, DIJ:4 },
      deger:   ['BAG','GUV'],
      kisilik: { S:5, DD:3 },
      isler:   'Arazi ölçümü, kadastro ve imar uygulamaları, coğrafi bilgi sistemleri, uydu ve drone verisi işleme.',
      not:     'Arazi çalışması hava koşullarına açıktır, mezunların bir bölümü serbest harita bürosu kurar.'
    },
    {
      kod: 'MALZEME_MUH',
      ad: 'Malzeme Bilimi ve Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'IRC',
      yetenek: { SOZ:2, SAY:5, MAN:5, UZM:4, VER:5 },
      beceri:  { SAY:5, SOZ:2, TEK:5, TAS:1, LID:2, DIJ:3 },
      deger:   ['BAS','BAG'],
      kisilik: { A:4, S:4 },
      isler:   'Malzeme geliştirme, mikroyapı analizi, kaplama ve ısıl işlem, hasar incelemesi.',
      not:     'Laboratuvar ağırlıklı bir alandır, iş ilanlarının çoğu yüksek lisans bekler.'
    },
    {
      kod: 'MEKATRONIK_MUH',
      ad: 'Mekatronik Mühendisliği',
      grup: 'Mühendislik ve teknoloji',
      puan: 'SAY',
      holland: 'RIC',
      yetenek: { SOZ:2, SAY:5, MAN:5, UZM:5, VER:3 },
      beceri:  { SAY:4, SOZ:2, TEK:5, TAS:2, LID:2, DIJ:5 },
      deger:   ['BAS','BAG'],
      kisilik: { A:5, S:4 },
      isler:   'Otomasyon sistemleri kurma, robot programlama, sensör ve kontrol tasarımı, üretim hattı bakımı.',
      not:     'Makine ile elektroniğin kesişimindedir, birinde derinleşmeyen mezun iki alanın uzmanıyla da yarışamaz.'
    },

    {
      kod: 'MATEMATIK',
      ad: 'Matematik',
      grup: 'Temel bilimler',
      puan: 'SAY',
      holland: 'ICA',
      yetenek: { SOZ:3, SAY:5, MAN:5, UZM:3, VER:4 },
      beceri:  { SAY:5, SOZ:3, TEK:1, TAS:1, LID:1, DIJ:3 },
      deger:   ['BAG','BAS'],
      kisilik: { S:5, A:4 },
      isler:   'Akademik araştırma, öğretmenlik, veri analizi, sigorta ve finans hesaplamaları.',
      not:     'Lisansın kendisi doğrudan bir mesleğe götürmez, öğretmenlik için pedagojik formasyon gerekir.'
    },
    {
      kod: 'FIZIK',
      ad: 'Fizik',
      grup: 'Temel bilimler',
      puan: 'SAY',
      holland: 'IRC',
      yetenek: { SOZ:2, SAY:5, MAN:5, UZM:4, VER:4 },
      beceri:  { SAY:5, SOZ:2, TEK:4, TAS:1, LID:1, DIJ:4 },
      deger:   ['BAG','BAS'],
      kisilik: { A:5, S:4 },
      isler:   'Laboratuvar araştırması, malzeme ve optik uygulamaları, medikal fizik, öğretmenlik.',
      not:     'İş bulma yolu çoğunlukla lisansüstü eğitimden geçer, sanayide doğrudan fizikçi kadrosu azdır.'
    },
    {
      kod: 'KIMYA',
      ad: 'Kimya',
      grup: 'Temel bilimler',
      puan: 'SAY',
      holland: 'IRC',
      yetenek: { SOZ:2, SAY:4, MAN:5, UZM:3, VER:4 },
      beceri:  { SAY:4, SOZ:2, TEK:5, TAS:1, LID:1, DIJ:3 },
      deger:   ['BAS','GUV'],
      kisilik: { S:5, DD:4 },
      isler:   'Analiz laboratuvarı çalışması, kalite kontrol, ürün geliştirme, öğretmenlik.',
      not:     'Kimya Mühendisliğiyle karıştırılır, bu bölüm tesis tasarımı değil madde ve tepkime üzerine çalışır.'
    },
    {
      kod: 'BIYOLOJI',
      ad: 'Biyoloji',
      grup: 'Temel bilimler',
      puan: 'SAY',
      holland: 'IRC',
      yetenek: { SOZ:3, SAY:3, MAN:4, UZM:3, VER:4 },
      beceri:  { SAY:3, SOZ:3, TEK:4, TAS:2, LID:1, DIJ:2 },
      deger:   ['BAG','KOS'],
      kisilik: { S:4, A:4 },
      isler:   'Saha ve laboratuvar araştırması, çevre izleme, biyolog kadrosu, öğretmenlik.',
      not:     'Lisans mezuniyetiyle iş alanı dardır, kadroların çoğu yüksek lisans sonrası açılır.'
    },
    {
      kod: 'MOLEKULER_BIYOLOJI_GENETIK',
      ad: 'Moleküler Biyoloji ve Genetik',
      grup: 'Temel bilimler',
      puan: 'SAY',
      holland: 'ICR',
      yetenek: { SOZ:3, SAY:4, MAN:5, UZM:2, VER:5 },
      beceri:  { SAY:4, SOZ:3, TEK:5, TAS:1, LID:1, DIJ:4 },
      deger:   ['BAS','BAG'],
      kisilik: { S:5, A:5 },
      isler:   'Genetik analiz, tanı laboratuvarı çalışması, ilaç ve biyoteknoloji araştırması, veri değerlendirme.',
      not:     'Deneyler uzun sürer ve çoğu sonuçsuz kalır, kariyer büyük ölçüde doktorayla şekillenir.'
    },
    {
      kod: 'ISTATISTIK',
      ad: 'İstatistik',
      grup: 'Temel bilimler',
      puan: 'SAY',
      holland: 'ICE',
      yetenek: { SOZ:3, SAY:5, MAN:5, UZM:1, VER:5 },
      beceri:  { SAY:5, SOZ:3, TEK:2, TAS:2, LID:2, DIJ:5 },
      deger:   ['BAS','GUV'],
      kisilik: { S:5, A:3 },
      isler:   'Veri analizi, anket ve örnekleme tasarımı, risk modelleme, raporlama.',
      not:     'Programlama öğrenmeden mezun olan aday veri analisti ilanlarında geri kalır.'
    },
    {
      kod: 'ASTRONOMI',
      ad: 'Astronomi ve Uzay Bilimleri',
      grup: 'Temel bilimler',
      puan: 'SAY',
      holland: 'IRA',
      yetenek: { SOZ:2, SAY:5, MAN:5, UZM:5, VER:5 },
      beceri:  { SAY:5, SOZ:2, TEK:3, TAS:1, LID:1, DIJ:5 },
      deger:   ['BAG','BAS'],
      kisilik: { A:5, S:4 },
      isler:   'Gözlem ve veri analizi, teleskopla ölçüm, akademik araştırma, planetaryum ve bilim iletişimi.',
      not:     'Ülke genelinde bölüm ve kadro sayısı çok azdır, iş alanı neredeyse tümüyle akademidir.'
    },

    {
      kod: 'HUKUK',
      ad: 'Hukuk',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'EIS',
      yetenek: { SOZ:5, SAY:2, MAN:5, UZM:1, VER:4 },
      beceri:  { SAY:2, SOZ:5, TEK:1, TAS:1, LID:4, DIJ:2 },
      deger:   ['TAN','BAG'],
      kisilik: { S:5, DD:4, D:4 },
      isler:   'Dava takibi, sözleşme hazırlama, hukuki danışmanlık, hakimlik ve savcılık.',
      not:     'Dört yılın ardından bir yıl staj ve baro sınavı vardır, mezun sayısı son on yılda hızla arttı.'
    },
    {
      kod: 'ISLETME',
      ad: 'İşletme',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'ECS',
      yetenek: { SOZ:4, SAY:4, MAN:4, UZM:1, VER:4 },
      beceri:  { SAY:4, SOZ:4, TEK:1, TAS:2, LID:5, DIJ:3 },
      deger:   ['TAN','BAS'],
      kisilik: { D:4, S:4 },
      isler:   'Pazarlama, finans yönetimi, insan kaynakları, satış ve operasyon.',
      not:     'Kontenjanı en geniş bölümlerden biridir, ayrışmak için staj ve yabancı dil gerekir.'
    },
    {
      kod: 'IKTISAT',
      ad: 'İktisat',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'IEC',
      yetenek: { SOZ:4, SAY:5, MAN:5, UZM:1, VER:5 },
      beceri:  { SAY:5, SOZ:4, TEK:1, TAS:1, LID:3, DIJ:3 },
      deger:   ['BAS','TAN'],
      kisilik: { S:4, A:4 },
      isler:   'Ekonomik analiz, kamu uzmanlığı, finans sektörü, araştırma raporları.',
      not:     'İşletmeden farkı matematik ve model yüküdür, kamu uzmanlık sınavları mezunların başlıca hedefidir.'
    },
    {
      kod: 'ULUSLARARASI_ILISKILER',
      ad: 'Uluslararası İlişkiler',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'ESI',
      yetenek: { SOZ:5, SAY:2, MAN:4, UZM:1, VER:4 },
      beceri:  { SAY:2, SOZ:5, TEK:1, TAS:1, LID:4, DIJ:2 },
      deger:   ['TAN','BAS'],
      kisilik: { D:4, A:4, S:4 },
      isler:   'Dış politika analizi, diplomatik yazışma, uluslararası kuruluş uzmanlığı, dış ticaret.',
      not:     'Diplomatlık ayrı bir sınav yarışı gerektirir, yabancı dil olmadan bölüm işlevsiz kalır.'
    },
    {
      kod: 'SIYASET_KAMU_YONETIMI',
      ad: 'Siyaset Bilimi ve Kamu Yönetimi',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'ESC',
      yetenek: { SOZ:5, SAY:3, MAN:4, UZM:1, VER:4 },
      beceri:  { SAY:3, SOZ:5, TEK:1, TAS:1, LID:4, DIJ:2 },
      deger:   ['GUV','TAN'],
      kisilik: { D:4, S:4 },
      isler:   'Kamu kurumlarında uzmanlık, kaymakamlık, yerel yönetim işleri, politika analizi.',
      not:     'Mezuniyet sonrası yol büyük ölçüde KPSS ve kurum sınavlarından geçer.'
    },
    {
      kod: 'MALIYE',
      ad: 'Maliye',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'CEI',
      yetenek: { SOZ:4, SAY:5, MAN:4, UZM:1, VER:5 },
      beceri:  { SAY:5, SOZ:3, TEK:1, TAS:1, LID:3, DIJ:3 },
      deger:   ['GUV','BAS'],
      kisilik: { S:5, U:3 },
      isler:   'Vergi denetimi, bütçe ve mali analiz, muhasebe denetimi, mali müşavirlik.',
      not:     'Mevzuat sürekli değişir, denetim kadrosu sınavları mezuniyetten sonra yıllarca çalışma ister.'
    },
    {
      kod: 'EKONOMETRI',
      ad: 'Ekonometri',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'ICE',
      yetenek: { SOZ:3, SAY:5, MAN:5, UZM:1, VER:5 },
      beceri:  { SAY:5, SOZ:3, TEK:1, TAS:1, LID:2, DIJ:5 },
      deger:   ['BAS','BAG'],
      kisilik: { S:5, A:4 },
      isler:   'Ekonomik veri modelleme, tahmin çalışmaları, risk analizi, finansal araştırma.',
      not:     'İktisadın matematik ağırlıklı koludur, istatistik dersleri birinci sınıftan itibaren yoğundur.'
    },
    {
      kod: 'PSIKOLOJI',
      ad: 'Psikoloji',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'ISA',
      yetenek: { SOZ:5, SAY:3, MAN:5, UZM:1, VER:5 },
      beceri:  { SAY:3, SOZ:5, TEK:1, TAS:2, LID:2, DIJ:3 },
      deger:   ['ILI','BAS'],
      kisilik: { U:4, A:5, S:4 },
      isler:   'Psikolojik değerlendirme, danışmanlık, insan kaynakları, araştırma ve ölçek çalışmaları.',
      not:     'Terapi yapabilmek için lisansüstü eğitim ve süpervizyon gerekir, lisans diploması tek başına yetmez.'
    },
    {
      kod: 'SOSYOLOJI',
      ad: 'Sosyoloji',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'ISC',
      yetenek: { SOZ:5, SAY:3, MAN:4, UZM:1, VER:5 },
      beceri:  { SAY:3, SOZ:5, TEK:1, TAS:1, LID:2, DIJ:3 },
      deger:   ['BAG','ILI'],
      kisilik: { A:5, U:4 },
      isler:   'Saha araştırması, sosyal politika çalışmaları, kurum içi araştırma, veri toplama ve yorumlama.',
      not:     'Doğrudan bir meslek tanımı yoktur, iş alanı çoğunlukla araştırma şirketleri ve kamu projeleridir.'
    },
    {
      kod: 'HALKLA_ILISKILER',
      ad: 'Halkla İlişkiler ve Tanıtım',
      grup: 'Sosyal ve idari',
      puan: 'SOZ',
      holland: 'ESA',
      yetenek: { SOZ:5, SAY:2, MAN:3, UZM:2, VER:3 },
      beceri:  { SAY:2, SOZ:5, TEK:1, TAS:3, LID:4, DIJ:4 },
      deger:   ['ILI','TAN'],
      kisilik: { D:5, U:4 },
      isler:   'Kurumsal iletişim, basın ilişkileri, etkinlik yönetimi, sosyal medya yürütme.',
      not:     'İşin ölçüsü kurulan ilişki ağıdır, mesai kampanya dönemlerinde akşamlara taşar.'
    },
    {
      kod: 'INSAN_KAYNAKLARI',
      ad: 'İnsan Kaynakları Yönetimi',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'SEC',
      yetenek: { SOZ:4, SAY:3, MAN:4, UZM:1, VER:4 },
      beceri:  { SAY:3, SOZ:5, TEK:1, TAS:1, LID:4, DIJ:3 },
      deger:   ['ILI','GUV'],
      kisilik: { D:4, U:4, S:4 },
      isler:   'İşe alım, eğitim planlama, performans sistemi kurma, özlük ve bordro takibi.',
      not:     'Günlük işin önemli kısmı mevzuat ve kayıttır, işten çıkarma görüşmelerini yürütmek de bu göreve dahildir.'
    },
    {
      kod: 'BANKACILIK_FINANS',
      ad: 'Bankacılık ve Finans',
      grup: 'Sosyal ve idari',
      puan: 'EA',
      holland: 'ECI',
      yetenek: { SOZ:4, SAY:5, MAN:4, UZM:1, VER:5 },
      beceri:  { SAY:5, SOZ:4, TEK:1, TAS:1, LID:3, DIJ:4 },
      deger:   ['BAS','TAN'],
      kisilik: { D:4, S:5 },
      isler:   'Kredi değerlendirme, portföy yönetimi, şube operasyonu, finansal analiz.',
      not:     'Şube tarafında hedef ve satış baskısı vardır, terfi çoğu zaman satış rakamına bağlıdır.'
    },

    {
      kod: 'SINIF_OGRETMENLIGI',
      ad: 'Sınıf Öğretmenliği',
      grup: 'Eğitim',
      puan: 'TYT',
      holland: 'SCA',
      yetenek: { SOZ:5, SAY:3, MAN:3, UZM:2, VER:3 },
      beceri:  { SAY:3, SOZ:5, TEK:1, TAS:3, LID:4, DIJ:2 },
      deger:   ['ILI','GUV'],
      kisilik: { U:5, S:5, DD:4 },
      isler:   'Aynı sınıfı dört yıl okutma, okuma yazma öğretimi, veli görüşmeleri, sınıf yönetimi.',
      not:     'Atama kontenjanı başvuru sayısının çok altındadır, ilk görev yeri genellikle küçük yerleşim yerleridir.'
    },
    {
      kod: 'MATEMATIK_OGRETMENLIGI',
      ad: 'Matematik Öğretmenliği',
      grup: 'Eğitim',
      puan: 'SAY',
      holland: 'SIC',
      yetenek: { SOZ:3, SAY:5, MAN:5, UZM:3, VER:4 },
      beceri:  { SAY:5, SOZ:5, TEK:1, TAS:2, LID:4, DIJ:3 },
      deger:   ['ILI','GUV'],
      kisilik: { S:5, U:4 },
      isler:   'Matematik dersleri, soru çözüm teknikleri, ölçme ve değerlendirme, öğrenci takibi.',
      not:     'Alanı bilmek yetmez, ergenlik çağındaki bir sınıfı yönetmek işin asıl zorlayan kısmıdır.'
    },
    {
      kod: 'FEN_BILGISI_OGRETMENLIGI',
      ad: 'Fen Bilgisi Öğretmenliği',
      grup: 'Eğitim',
      puan: 'SAY',
      holland: 'SIR',
      yetenek: { SOZ:4, SAY:4, MAN:4, UZM:3, VER:4 },
      beceri:  { SAY:4, SOZ:5, TEK:3, TAS:2, LID:4, DIJ:3 },
      deger:   ['ILI','GUV'],
      kisilik: { S:5, U:4, A:4 },
      isler:   'Fen derslerini yürütme, deney düzeneği kurma, proje çalışmaları, ölçme ve değerlendirme.',
      not:     'Üç ayrı bilim alanından birden sorumlu olursunuz, okul laboratuvarları çoğu zaman eksiktir.'
    },
    {
      kod: 'TURKCE_OGRETMENLIGI',
      ad: 'Türkçe Öğretmenliği',
      grup: 'Eğitim',
      puan: 'SOZ',
      holland: 'SAC',
      yetenek: { SOZ:5, SAY:1, MAN:4, UZM:1, VER:3 },
      beceri:  { SAY:1, SOZ:5, TEK:1, TAS:2, LID:4, DIJ:2 },
      deger:   ['ILI','GUV'],
      kisilik: { U:4, S:5, A:4 },
      isler:   'Dil bilgisi öğretimi, metin çözümleme, yazma çalışmaları, sınıf içi tartışma yönetimi.',
      not:     'Her yıl binlerce mezun verilir, atama taban puanı öğretmenlikler arasında en çekişmeli olanlardandır.'
    },
    {
      kod: 'INGILIZCE_OGRETMENLIGI',
      ad: 'İngilizce Öğretmenliği',
      grup: 'Eğitim',
      puan: 'DIL',
      holland: 'SAE',
      yetenek: { SOZ:5, SAY:1, MAN:4, UZM:1, VER:3 },
      beceri:  { SAY:1, SOZ:5, TEK:1, TAS:2, LID:4, DIJ:3 },
      deger:   ['ILI','KOS'],
      kisilik: { D:4, U:4, S:4 },
      isler:   'Yabancı dil dersleri, konuşma ve dinleme etkinlikleri, materyal hazırlama, sınav hazırlığı.',
      not:     'Bölüme YDT ile girilir, dil yeterliliğinin lisede büyük ölçüde kazanılmış olması beklenir.'
    },
    {
      kod: 'OKUL_ONCESI_OGRETMENLIGI',
      ad: 'Okul Öncesi Öğretmenliği',
      grup: 'Eğitim',
      puan: 'TYT',
      holland: 'SAR',
      yetenek: { SOZ:4, SAY:2, MAN:3, UZM:2, VER:2 },
      beceri:  { SAY:1, SOZ:5, TEK:2, TAS:4, LID:4, DIJ:2 },
      deger:   ['ILI','KOS'],
      kisilik: { U:5, DD:5, D:4 },
      isler:   'Etkinlik planlama, oyun ve sanat çalışmaları, gelişim takibi, aile görüşmeleri.',
      not:     'Gün boyu ayakta ve yüksek sesli bir ortamdır, küçük çocukların bakım işleri de öğretmene aittir.'
    },
    {
      kod: 'OZEL_EGITIM_OGRETMENLIGI',
      ad: 'Özel Eğitim Öğretmenliği',
      grup: 'Eğitim',
      puan: 'TYT',
      holland: 'SCR',
      yetenek: { SOZ:4, SAY:2, MAN:4, UZM:2, VER:4 },
      beceri:  { SAY:2, SOZ:5, TEK:3, TAS:2, LID:3, DIJ:2 },
      deger:   ['ILI','GUV'],
      kisilik: { U:5, DD:5, S:5 },
      isler:   'Bireysel eğitim programı hazırlama, davranış yönetimi, beceri öğretimi, aile rehberliği.',
      not:     'İlerleme çok yavaştır, öğrencinin öfke ve saldırganlık davranışlarıyla karşılaşmak olağandır.'
    },
    {
      kod: 'PDR',
      ad: 'Rehberlik ve Psikolojik Danışmanlık',
      grup: 'Eğitim',
      puan: 'EA',
      holland: 'SIE',
      yetenek: { SOZ:5, SAY:2, MAN:4, UZM:1, VER:4 },
      beceri:  { SAY:2, SOZ:5, TEK:1, TAS:2, LID:4, DIJ:2 },
      deger:   ['ILI','BAS'],
      kisilik: { U:5, S:4, DD:4 },
      isler:   'Öğrenci görüşmeleri, test ve envanter uygulama, meslek seçimi rehberliği, kriz durumlarında destek.',
      not:     'Okulda rehber öğretmene nöbet ve evrak işleri de verilir, görüşmeye ayrılan süre sanılandan azdır.'
    },

    {
      kod: 'TURK_DILI_EDEBIYATI',
      ad: 'Türk Dili ve Edebiyatı',
      grup: 'Dil ve edebiyat',
      puan: 'SOZ',
      holland: 'ASI',
      yetenek: { SOZ:5, SAY:1, MAN:4, UZM:1, VER:3 },
      beceri:  { SAY:1, SOZ:5, TEK:1, TAS:2, LID:2, DIJ:2 },
      deger:   ['BAG','ILI'],
      kisilik: { A:5, S:4 },
      isler:   'Metin inceleme, editörlük, öğretmenlik, arşiv ve yayın çalışmaları.',
      not:     'Osmanlı Türkçesi ve eski metin dersleri bölümün çekirdeğidir, roman okumaktan ibaret değildir.'
    },
    {
      kod: 'INGILIZ_DILI_EDEBIYATI',
      ad: 'İngiliz Dili ve Edebiyatı',
      grup: 'Dil ve edebiyat',
      puan: 'DIL',
      holland: 'AIS',
      yetenek: { SOZ:5, SAY:1, MAN:4, UZM:1, VER:3 },
      beceri:  { SAY:1, SOZ:5, TEK:1, TAS:1, LID:2, DIJ:2 },
      deger:   ['BAG','KOS'],
      kisilik: { A:5, S:4 },
      isler:   'İngiliz edebiyatı incelemesi, çeviri, öğretmenlik, akademik araştırma.',
      not:     'Dil öğrenme bölümü değildir, dersler ilk günden edebiyat kuramı ve eski metinler üzerine kurulur.'
    },
    {
      kod: 'MUTERCIM_TERCUMANLIK',
      ad: 'Mütercim ve Tercümanlık',
      grup: 'Dil ve edebiyat',
      puan: 'DIL',
      holland: 'ACS',
      yetenek: { SOZ:5, SAY:1, MAN:4, UZM:1, VER:4 },
      beceri:  { SAY:1, SOZ:5, TEK:1, TAS:1, LID:2, DIJ:4 },
      deger:   ['BAG','KOS'],
      kisilik: { S:5, A:4, DD:4 },
      isler:   'Yazılı çeviri, ardıl ve simultane çeviri, altyazı ve yerelleştirme, terim çalışması.',
      not:     'Makine çevirisi yazılı işin ücretini düşürdü, ayakta kalan kısım sözlü çeviri ve uzmanlık alanlarıdır.'
    },
    {
      kod: 'TARIH',
      ad: 'Tarih',
      grup: 'Dil ve edebiyat',
      puan: 'SOZ',
      holland: 'IAC',
      yetenek: { SOZ:5, SAY:1, MAN:4, UZM:2, VER:4 },
      beceri:  { SAY:1, SOZ:5, TEK:1, TAS:1, LID:2, DIJ:2 },
      deger:   ['BAG','BAS'],
      kisilik: { A:4, S:5 },
      isler:   'Arşiv araştırması, öğretmenlik, müze ve kültür kurumları, yayın ve editörlük.',
      not:     'Ezber değil kaynak eleştirisi ister, akademi dışında açılan kadro sayısı sınırlıdır.'
    },
    {
      kod: 'ARKEOLOJI',
      ad: 'Arkeoloji',
      grup: 'Dil ve edebiyat',
      puan: 'EA',
      holland: 'IRA',
      yetenek: { SOZ:4, SAY:2, MAN:4, UZM:4, VER:4 },
      beceri:  { SAY:2, SOZ:3, TEK:4, TAS:3, LID:2, DIJ:2 },
      deger:   ['BAG','BAS'],
      kisilik: { S:5, A:4, DD:4 },
      isler:   'Kazı çalışması, buluntu belgeleme, müze uzmanlığı, koruma ve restorasyon projeleri.',
      not:     'Yaz ayları sıcak arazide kazıyla geçer, kamu kadrosu her yıl çok az sayıda açılır.'
    },
    {
      kod: 'FELSEFE',
      ad: 'Felsefe',
      grup: 'Dil ve edebiyat',
      puan: 'EA',
      holland: 'IAS',
      yetenek: { SOZ:5, SAY:2, MAN:5, UZM:1, VER:3 },
      beceri:  { SAY:2, SOZ:5, TEK:1, TAS:1, LID:2, DIJ:2 },
      deger:   ['BAG','BAS'],
      kisilik: { A:5, S:4 },
      isler:   'Metin çözümleme, öğretmenlik, yayıncılık, mantık ve etik alanında danışmanlık.',
      not:     'Argüman kurmayı ve ağır okumayı gerektirir, bazı üniversitelerde SÖZ puanıyla da öğrenci alınır.'
    },

    {
      kod: 'MIMARLIK',
      ad: 'Mimarlık',
      grup: 'Sanat ve tasarım',
      puan: 'SAY',
      holland: 'AIR',
      yetenek: { SOZ:3, SAY:4, MAN:4, UZM:5, VER:3 },
      beceri:  { SAY:3, SOZ:3, TEK:4, TAS:5, LID:3, DIJ:4 },
      deger:   ['BAS','BAG'],
      kisilik: { A:5, S:4, DD:4 },
      isler:   'Bina tasarımı, proje çizimi, şantiye takibi, restorasyon ve iç mekan projeleri.',
      not:     'Stüdyo derslerinde gece çalışması olağandır, bitirilen her proje jüri önünde eleştiriye açılır.'
    },
    {
      kod: 'IC_MIMARLIK',
      ad: 'İç Mimarlık',
      grup: 'Sanat ve tasarım',
      puan: 'SAY',
      holland: 'ARE',
      yetenek: { SOZ:3, SAY:3, MAN:3, UZM:5, VER:2 },
      beceri:  { SAY:2, SOZ:4, TEK:4, TAS:5, LID:3, DIJ:4 },
      deger:   ['BAG','BAS'],
      kisilik: { A:5, D:4 },
      isler:   'Mekan tasarımı, malzeme ve mobilya seçimi, uygulama takibi, müşteri sunumu.',
      not:     'İşin büyük kısmı müşteri beklentisiyle bütçe arasında uzlaşma aramaktır.'
    },
    {
      kod: 'ENDUSTRIYEL_TASARIM',
      ad: 'Endüstriyel Tasarım',
      grup: 'Sanat ve tasarım',
      puan: 'SAY',
      holland: 'ARI',
      yetenek: { SOZ:3, SAY:3, MAN:4, UZM:5, VER:3 },
      beceri:  { SAY:3, SOZ:3, TEK:4, TAS:5, LID:3, DIJ:5 },
      deger:   ['BAS','BAG'],
      kisilik: { A:5, S:4 },
      isler:   'Ürün tasarımı, kullanıcı araştırması, prototip üretimi, üretim ekibiyle çalışma.',
      not:     'Tasarımın üretilebilir ve hesaplı olması sınırı belirler, serbest çizim payı sanıldığından azdır.'
    },
    {
      kod: 'GRAFIK_TASARIM',
      ad: 'Grafik Tasarım',
      grup: 'Sanat ve tasarım',
      puan: 'OZEL',
      holland: 'AEC',
      yetenek: { SOZ:3, SAY:1, MAN:3, UZM:4, VER:2 },
      beceri:  { SAY:1, SOZ:3, TEK:2, TAS:5, LID:2, DIJ:5 },
      deger:   ['BAG','TAN'],
      kisilik: { A:5, D:3 },
      isler:   'Kurumsal kimlik tasarımı, reklam görselleri, ambalaj, dijital arayüz görselleri.',
      not:     'Bölüme yetenek sınavı ve portfolyo ile girilir, serbest çalışmada gelir aydan aya değişir.'
    },
    {
      kod: 'RESIM',
      ad: 'Resim',
      grup: 'Sanat ve tasarım',
      puan: 'OZEL',
      holland: 'ARS',
      yetenek: { SOZ:3, SAY:1, MAN:2, UZM:5, VER:1 },
      beceri:  { SAY:1, SOZ:2, TEK:3, TAS:5, LID:1, DIJ:3 },
      deger:   ['BAG','TAN'],
      kisilik: { A:5, S:3 },
      isler:   'Özgün eser üretimi, sergi hazırlığı, atölye çalışması, öğretmenlik ve eğitmenlik.',
      not:     'Eser satışıyla düzenli gelire ulaşmak uzun yıllar alır, mezunların çoğu eğitim tarafında çalışır.'
    },
    {
      kod: 'MUZIK',
      ad: 'Müzik',
      grup: 'Sanat ve tasarım',
      puan: 'OZEL',
      holland: 'ASR',
      yetenek: { SOZ:3, SAY:2, MAN:3, UZM:3, VER:1 },
      beceri:  { SAY:1, SOZ:3, TEK:4, TAS:3, LID:2, DIJ:3 },
      deger:   ['BAG','TAN'],
      kisilik: { A:5, S:5, DD:4 },
      isler:   'Enstrüman icrası, orkestra ve topluluk çalışmaları, beste ve düzenleme, müzik eğitmenliği.',
      not:     'Yetenek sınavına hazırlığın lise yıllarında başlamış olması beklenir, günlük çalışma saati profesyonel sporcununkine benzer.'
    },
    {
      kod: 'SAHNE_SANATLARI',
      ad: 'Sahne Sanatları',
      grup: 'Sanat ve tasarım',
      puan: 'OZEL',
      holland: 'ASE',
      yetenek: { SOZ:5, SAY:1, MAN:3, UZM:3, VER:1 },
      beceri:  { SAY:1, SOZ:5, TEK:2, TAS:3, LID:3, DIJ:2 },
      deger:   ['TAN','BAG'],
      kisilik: { D:5, A:5, DD:4 },
      isler:   'Sahne ve kamera oyunculuğu, rol çalışması, ses ve beden eğitimi, yönetmenle prova.',
      not:     'İş bulmak seçmelere bağlıdır ve gelir dönem dönem tümüyle kesilir.'
    },
    {
      kod: 'PEYZAJ_MIMARLIGI',
      ad: 'Peyzaj Mimarlığı',
      grup: 'Sanat ve tasarım',
      puan: 'SAY',
      holland: 'RAI',
      yetenek: { SOZ:3, SAY:3, MAN:3, UZM:5, VER:3 },
      beceri:  { SAY:3, SOZ:3, TEK:4, TAS:5, LID:3, DIJ:4 },
      deger:   ['KOS','BAG'],
      kisilik: { A:4, S:4 },
      isler:   'Açık alan tasarımı, bitki seçimi, park ve kent projeleri, uygulama denetimi.',
      not:     'Bitki bilgisi ve ekoloji dersleri ağırlıklıdır, işler büyük ölçüde belediye ihalelerine bağlıdır.'
    },

    {
      kod: 'GAZETECILIK',
      ad: 'Gazetecilik',
      grup: 'İletişim ve medya',
      puan: 'SOZ',
      holland: 'EIA',
      yetenek: { SOZ:5, SAY:2, MAN:4, UZM:1, VER:4 },
      beceri:  { SAY:2, SOZ:5, TEK:2, TAS:2, LID:3, DIJ:4 },
      deger:   ['BAG','TAN'],
      kisilik: { D:4, A:4, DD:4 },
      isler:   'Haber toplama, röportaj, metin yazımı, dijital yayın düzenleme.',
      not:     'Çalışma saatleri olayın akışına göre değişir, sektörde iş güvencesi düşüktür.'
    },
    {
      kod: 'RADYO_TV_SINEMA',
      ad: 'Radyo, Televizyon ve Sinema',
      grup: 'İletişim ve medya',
      puan: 'SOZ',
      holland: 'AER',
      yetenek: { SOZ:4, SAY:2, MAN:3, UZM:4, VER:2 },
      beceri:  { SAY:2, SOZ:4, TEK:4, TAS:4, LID:3, DIJ:5 },
      deger:   ['BAG','TAN'],
      kisilik: { A:5, D:4 },
      isler:   'Senaryo yazımı, çekim ve kurgu, yapım koordinasyonu, içerik üretimi.',
      not:     'Setteki ilk yıllar asistanlıkla ve uzun saatlerle geçer, çalışma çoğunlukla proje başınadır.'
    },
    {
      kod: 'REKLAMCILIK',
      ad: 'Reklamcılık',
      grup: 'İletişim ve medya',
      puan: 'SOZ',
      holland: 'EAS',
      yetenek: { SOZ:5, SAY:3, MAN:4, UZM:2, VER:4 },
      beceri:  { SAY:3, SOZ:5, TEK:1, TAS:4, LID:4, DIJ:5 },
      deger:   ['TAN','BAS'],
      kisilik: { D:5, A:5 },
      isler:   'Kampanya planlama, metin yazarlığı, marka stratejisi, dijital reklam yönetimi.',
      not:     'Teslim süreleri kısadır ve işin başarısı satış rakamıyla ölçülür.'
    },
    {
      kod: 'YENI_MEDYA',
      ad: 'Yeni Medya ve İletişim',
      grup: 'İletişim ve medya',
      puan: 'SOZ',
      holland: 'AEI',
      yetenek: { SOZ:4, SAY:3, MAN:4, UZM:2, VER:5 },
      beceri:  { SAY:3, SOZ:4, TEK:2, TAS:4, LID:3, DIJ:5 },
      deger:   ['BAG','BAS'],
      kisilik: { A:5, D:4 },
      isler:   'Dijital içerik üretimi, sosyal medya yönetimi, veri ve etkileşim analizi, marka iletişimi.',
      not:     'Platform kuralları hızla değişir, bugün öğrenilen araç birkaç yıl içinde geçerliliğini yitirebilir.'
    },
    {
      kod: 'GORSEL_ILETISIM_TASARIMI',
      ad: 'Görsel İletişim Tasarımı',
      grup: 'İletişim ve medya',
      puan: 'SOZ',
      holland: 'AIE',
      yetenek: { SOZ:3, SAY:2, MAN:3, UZM:5, VER:3 },
      beceri:  { SAY:2, SOZ:3, TEK:2, TAS:5, LID:2, DIJ:5 },
      deger:   ['BAG','TAN'],
      kisilik: { A:5, S:4 },
      isler:   'Arayüz tasarımı, hareketli grafik, video ve fotoğraf işleri, marka görselleri.',
      not:     'Bazı üniversiteler bu bölüme özel yetenek sınavıyla öğrenci alır, işe girişte portfolyo mezuniyet notundan daha belirleyicidir.'
    }

  ]
};
