// Kişilik Envanteri madde havuzu. Beş Faktör modeli, 70 madde, boyut başına 14.
var KOK = (typeof window !== 'undefined') ? window : global;

KOK.ENV_KISILIK = {
  kod: 'KISILIK',
  ad: 'Kişilik Envanteri',
  olcek: ['Hiç uymuyor', 'Az uyuyor', 'Kısmen uyuyor', 'Çoğunlukla uyuyor', 'Tamamen uyuyor'],
  boyutlar: [
    { k:'D', ad:'Dışadönüklük', aciklama:'Sosyal ortamlarda ne kadar enerji harcadığını ve enerjini nereden topladığını gösterir. Yüksek puan kalabalıkta canlanmayı, düşük puan az kişiyle sakin bir iletişimi tercih etmeyi anlatır.' },
    { k:'U', ad:'Uyumluluk', aciklama:'İnsanlarla ilişki kurarken uzlaşmaya mı yoksa kendi konumunu korumaya mı yöneldiğini gösterir. Yüksek puan destekleyici ve hoşgörülü bir tutumu, düşük puan doğrudan ve rekabete açık bir tutumu anlatır.' },
    { k:'S', ad:'Sorumluluk', aciklama:'Planlama, düzen ve görev takibi konusundaki eğilimini gösterir. Yüksek puan programlı ve titiz çalışmayı, düşük puan esnek ve anlık ilerlemeyi anlatır.' },
    { k:'DD', ad:'Duygusal denge', aciklama:'Günlük gerginlikler ve aksilikler karşısında duygularının ne kadar dalgalandığını gösterir. Yüksek puan olaylar karşısında sakin kalmayı, düşük puan daha hızlı ve yoğun tepki vermeyi anlatır.' },
    { k:'A', ad:'Deneyime açıklık', aciklama:'Yeni fikirlere, farklı deneyimlere ve alışılmadık yollara duyduğun ilgiyi gösterir. Yüksek puan merakı ve değişime açıklığı, düşük puan tanıdık ve denenmiş olanı tercih etmeyi anlatır.' }
  ],
  maddeler: [
    { n:1, m:'Alıştığım düzenin dışına çıkmak beni rahatsız eder.', b:'A', t:true },
    { n:2, m:'Tartışırken karşımdakinin haklı olabileceğini düşünürüm.', b:'U', t:false },
    { n:3, m:'Ders çalıştığım masa dağınık durur.', b:'S', t:true },
    { n:4, m:'Grup ödevlerinde sunumu yapmaya gönüllü olurum.', b:'D', t:false },
    { n:5, m:'Küçük aksiliklerde bile canım kolayca sıkılır.', b:'DD', t:true },
    { n:6, m:'Daha önce tatmadığım bir yemeği denemek isterim.', b:'A', t:false },
    { n:7, m:'Verdiğim sözleri sonradan unuturum.', b:'S', t:true },
    { n:8, m:'Sınav öncesinde sakin kalabilirim.', b:'DD', t:false },
    { n:9, m:'Beni kıran biriyle uzun süre konuşmam.', b:'U', t:true },
    { n:10, m:'Hafta sonu buluşma planını genelde ben başlatırım.', b:'D', t:false },
    { n:11, m:'Hayal kurmak yerine somut işlerle ilgilenirim.', b:'A', t:true },
    { n:12, m:'Okul çantamı bir akşam önceden hazırlarım.', b:'S', t:false },
    { n:13, m:'Çoğu kişi fırsat bulsa beni kullanır diye düşünürüm.', b:'U', t:true },
    { n:14, m:'Düşük not aldığımda kısa sürede toparlanırım.', b:'DD', t:false },
    { n:15, m:'Yeni bir ortama girdiğimde bir köşede beklerim.', b:'D', t:true },
    { n:16, m:'Sanat etkinliklerine katılmak ilgimi çeker.', b:'A', t:false },
    { n:17, m:'Derste yaptığım bir hata günlerce aklımdan çıkmaz.', b:'DD', t:true },
    { n:18, m:'Kalabalık bir doğum günü kutlamasında enerjim artar.', b:'D', t:false },
    { n:19, m:'Grup ödevi benim dediğim gibi yürümezse işten çekilirim.', b:'U', t:true },
    { n:20, m:'Uzun proje ödevini küçük parçalara bölerek ilerlerim.', b:'S', t:false },
    { n:21, m:'Soyut konuları konuşmak bana gereksiz gelir.', b:'A', t:true },
    { n:22, m:'Biri hata yaptığında kötü niyetli olmadığını varsayarım.', b:'U', t:false },
    { n:23, m:'Tanımadığım kişilerin yanında sessiz kalırım.', b:'D', t:true },
    { n:24, m:'Buluşma yerine söz verdiğim saatte varırım.', b:'S', t:false },
    { n:25, m:'Ertesi güne dair kaygılarım akşam boyunca zihnimi meşgul eder.', b:'DD', t:true },
    { n:26, m:'Hiç dinlemediğim bir müzik türünü merak ederim.', b:'A', t:false },
    { n:27, m:'Büyük grup sohbetlerinde araya girmekte zorlanırım.', b:'D', t:true },
    { n:28, m:'Sınıfta dışlanan birine yanımda yer açarım.', b:'U', t:false },
    { n:29, m:'Çalışma planı yapsam da uygulamayı sürdüremem.', b:'S', t:true },
    { n:30, m:'Yoğun ders programı beni fazla germez.', b:'DD', t:false },
    { n:31, m:'Yeni yöntemler yerine bildiğim yolu kullanırım.', b:'A', t:true },
    { n:32, m:'Sınıfa yeni gelen biriyle ilk ben konuşurum.', b:'D', t:false },
    { n:33, m:'Tartışmalarda son sözü söylemeden rahat edemem.', b:'U', t:true },
    { n:34, m:'Ödevlerimi teslim tarihinden önce bitiririm.', b:'S', t:false },
    { n:35, m:'Sınav sonucunu beklerken huzursuz olurum.', b:'DD', t:true },
    { n:36, m:'Boş vaktimde yeni bir beceri öğrenmeye çalışırım.', b:'A', t:false },
    { n:37, m:'Arkadaş davetlerini çoğu zaman geri çevirip evde kalırım.', b:'D', t:true },
    { n:38, m:'Konu tekrarını ertelemeden aynı gün yaparım.', b:'S', t:false },
    { n:39, m:'İnsanların hatalarını yüzlerine vurmaktan çekinmem.', b:'U', t:true },
    { n:40, m:'Sunum yaparken heyecanımı kontrol edebilirim.', b:'DD', t:false },
    { n:41, m:'Ödeve genellikle son gece başlarım.', b:'S', t:true },
    { n:42, m:'Tartışmalı bir konuda karşıt görüşü de okurum.', b:'A', t:false },
    { n:43, m:'Sosyal medyada gelen olumsuz yorumlar beni uzun süre meşgul eder.', b:'DD', t:true },
    { n:44, m:'Not defterimi isteyen arkadaşıma çekinmeden veririm.', b:'U', t:false },
    { n:45, m:'Derste söz almak yerine dinlemeyi tercih ederim.', b:'D', t:true },
    { n:46, m:'Arkadaşım üzgün göründüğünde ne olduğunu sorarım.', b:'U', t:false },
    { n:47, m:'Gezilerde tanıdık yerleri yeni yerlere tercih ederim.', b:'A', t:true },
    { n:48, m:'Tanımadığım biriyle konuşmaya ilk adımı ben atarım.', b:'D', t:false },
    { n:49, m:'Başladığım işi bitirmeden başka bir şeye geçerim.', b:'S', t:true },
    { n:50, m:'Eleştiri aldığımda savunmaya geçmeden dinleyebilirim.', b:'DD', t:false },
    { n:51, m:'Ders dışındaki konuları araştırmaya ilgi duymam.', b:'A', t:true },
    { n:52, m:'Anlaşmazlıkta sesimi yükseltmeden konuşmayı sürdürürüm.', b:'U', t:false },
    { n:53, m:'Sabah okula yetişmek için çoğu zaman acele ederim.', b:'S', t:true },
    { n:54, m:'Okul gezilerinde yol boyunca sohbet ederim.', b:'D', t:false },
    { n:55, m:'Planım bozulduğunda öfkem hemen yükselir.', b:'DD', t:true },
    { n:56, m:'Grup ödevinde başkasının önerisini denemeye açığım.', b:'U', t:false },
    { n:57, m:'Kalabalık ortamlarda uzun süre kalınca yorulurum.', b:'D', t:true },
    { n:58, m:'Derste anlatılan konunun nedenini kendim araştırırım.', b:'A', t:false },
    { n:59, m:'Ders çalışırken telefonu uzağa koyarım.', b:'S', t:false },
    { n:60, m:'Gün içinde ruh hâlim genelde aynı seyirde gider.', b:'DD', t:false },
    { n:61, m:'Arkadaşlarımın sorunlarını dinlemek bana zaman kaybı gibi gelir.', b:'U', t:true },
    { n:62, m:'Okul etkinliklerinde sahne almaktan çekinmem.', b:'D', t:false },
    { n:63, m:'Defterimin düzenli olması benim için önemlidir.', b:'S', t:false },
    { n:64, m:'Bir sorunu çözerken alışılmadık yollar denerim.', b:'A', t:false },
    { n:65, m:'Beklenmedik bir program değişikliğinde telaşlanmam.', b:'DD', t:false },
    { n:66, m:'Farklı ülkelerin yaşayış biçimlerini okumaktan hoşlanırım.', b:'A', t:false },
    { n:67, m:'Teneffüslerde başka sınıflardaki arkadaşlarımın yanına giderim.', b:'D', t:false },
    { n:68, m:'Arkadaşımla tartıştıktan sonra hızla sakinleşirim.', b:'DD', t:false },
    { n:69, m:'Sınav haftası için günlük çalışma planı hazırlarım.', b:'S', t:false },
    { n:70, m:'Arkadaşımın derdi uzun sürse de sonuna kadar dinlerim.', b:'U', t:false }
  ]
};
