/* Yetenek Testi. 40 soru, 5 alan, alan başına 8 soru.
   Doğru cevap d alanındaki indekstir, 0 = A seçeneği.
   z zorluk, 10 üzerinden, tavan 5. Uzamsal maddelerde g alanı çizim tarifidir. */

var KOK = (typeof window !== 'undefined') ? window : global;

KOK.ENV_YETENEK = {
  kod: 'YETENEK',
  ad: 'Yetenek Testi',
  sure: 45,

  boyutlar: [
    {
      "k": "SOZ",
      "ad": "Sözel akıl yürütme",
      "aciklama": "Sözcükler arasındaki ilişkiyi kurma, okuduğundan çıkarım yapma ve anlamca en yakın ifadeyi seçme gücünü ölçer. Hukuk, edebiyat, öğretmenlik ve iletişim alanlarında ağır basar."
    },
    {
      "k": "SAY",
      "ad": "Sayısal akıl yürütme",
      "aciklama": "Sayılarla işlem kurma, oran ve yüzde hesaplama, problemi denkleme çevirme gücünü ölçer. Mühendislik, temel bilimler ve finans alanlarında ağır basar."
    },
    {
      "k": "MAN",
      "ad": "Mantıksal akıl yürütme",
      "aciklama": "Verilen öncüllerden geçerli sonucu çıkarma ve kurala göre eleme yapma gücünü ölçer. Yazılım, hukuk ve araştırma alanlarında ağır basar."
    },
    {
      "k": "UZM",
      "ad": "Uzamsal düşünme",
      "aciklama": "Bir şeklin döndürülmüş, katlanmış ya da yansıtılmış hâlini zihinde canlandırma gücünü ölçer. Mimarlık, tasarım, cerrahi ve makine alanlarında ağır basar."
    },
    {
      "k": "VER",
      "ad": "Veri yorumlama",
      "aciklama": "Tablodan ve grafikten doğru okuma yapma, değişimi hesaplama ve veriden geçerli çıkarımı ayırt etme gücünü ölçer. İstatistik, iktisat, sağlık bilimleri ve yönetim alanlarında ağır basar."
    }
  ],

  maddeler: [
    {"n":1,"b":"SOZ","z":2,"d":2,"s":"Kitap ile sayfa arasındaki ilişkiye en çok benzeyen eşleşme hangisidir?","sec":["Kalem : Yazı","Ağaç : Orman","Bina : Kat","Öğretmen : Okul","Su : Bardak"],"ac":"Kitap sayfalardan oluşur, burada bütün ile parça ilişkisi vardır. Bina da katlardan oluştuğu için aynı ilişkiyi taşır. Ağaç ile orman eşleşmesinde yön terstir, orada ağaç parçadır. Kalem yazının aracı, bardak ise suyun kabıdır, ikisi de bütün parça ilişkisi değildir."},
    {"n":2,"b":"SOZ","z":3,"d":0,"s":"Bir okulun kantininde satılan ürünler yenilenmiş, şekerli içecekler raftan kaldırılmıştır. Bu değişiklikten sonra kantinde su satışı yükselmiş, günlük toplam satış tutarı ise düşmüştür. Buna göre paragraftan kesin olarak çıkarılabilecek yargı hangisidir?","sec":["Şekerli içecekler kaldırıldıktan sonra su satışı yükselmiştir.","Su, kantinde en çok satılan ürün durumuna gelmiştir.","Su satışının artması toplam satış tutarını düşürmüştür.","Değişiklikten önce kantinde su satılmıyordu.","Kantinden alışveriş yapan öğrenci sayısı azalmıştır."],"ac":"Paragraf, şekerli içeceklerin kaldırılmasından sonra su satışının yükseldiğini doğrudan söylüyor. Su satışının en yüksek olduğu ya da önceden su satılmadığı bilgisi metinde yok, artış tek başına bunları göstermez. Toplam tutarın düşmesi ile su satışının artması aynı dönemde görülür, ancak metin biri diğerine yol açtı demiyor. Öğrenci sayısı üzerine de veri verilmemiştir."},
    {"n":3,"b":"SOZ","z":3,"d":4,"s":"Otobüs saatinde kalkmasına rağmen ---- cümlesini anlamca en uygun biçimde tamamlayan ifade hangisidir?","sec":["yolcuların çoğu aynı duraktan bindi","yol boyunca hiç mola vermedik","şoför güzergâhı çok iyi biliyordu","hava sabahtan beri yağmurluydu","okula geç kaldık"],"ac":"Rağmen bağlacı, iki durum arasında karşıtlık kurulmasını ister. Otobüsün zamanında kalkması normalde zamanında varmayı beklettirir, bu beklentiyi bozan tek tamamlama geç kalmaktır. Diğer seçenekler cümleye yalnız ek bilgi katar, beklentiye ters bir durum bildirmez."},
    {"n":4,"b":"SOZ","z":2,"d":1,"s":"Konuyu anlatırken hiçbir ayrıntıyı atlamadı. cümlesiyle anlamca en yakın ifade hangisidir?","sec":["Konuyu çok kısa sürede anlattı.","Konuyu bütün ayrıntılarıyla anlattı.","Konuyu anlatırken ayrıntılara girmedi.","Konuyu yalnız birkaç ayrıntıyla anlattı.","Konuyu anlatırken zorlandı."],"ac":"Atlamadı sözcüğü olumsuz görünse de burada hiçbirini dışarıda bırakmadı anlamı taşır. Öyleyse ayrıntıların tamamı anlatılmıştır. Cümledeki olumsuzluk ekine bakıp ayrıntılara girmedi biçiminde okumak sık yapılan bir hatadır. Sürenin uzunluğu ya da anlatıcının zorlanması üzerine cümlede bilgi yoktur."},
    {"n":5,"b":"SOZ","z":4,"d":3,"s":"Bir okulda dört şube vardır. 9-A'nın mevcudu 9-B'den fazladır. 9-C'nin mevcudu 9-A'dan az, 9-B'den fazladır. 9-D'nin mevcudu ise 9-A'dan fazladır. Buna göre en kalabalık şube ile en az mevcutlu şube sırasıyla hangileridir?","sec":["9-A ve 9-B","9-D ve 9-C","9-A ve 9-C","9-D ve 9-B","9-C ve 9-B"],"ac":"Verilenleri tek bir sıraya dizelim: 9-D, 9-A'dan kalabalıktır; 9-A, 9-C'den kalabalıktır; 9-C de 9-B'den kalabalıktır. Sıralama 9-D, 9-A, 9-C, 9-B biçiminde olur. En kalabalık şube 9-D, en az mevcutlu şube 9-B'dir. 9-A'yı en kalabalık saymak, 9-D ile ilgili son bilgiyi hesaba katmamaktan doğar."},
    {"n":6,"b":"SOZ","z":3,"d":0,"s":"Susuzluk ile su arasındaki ilişkiye en çok benzeyen eşleşme hangisidir?","sec":["Yorgunluk : Dinlenme","Açlık : Mutfak","Uyku : Yatak","Hastalık : Doktor","Soğuk : Kış"],"ac":"Susuzluk bir ihtiyaçtır, su o ihtiyacı doğrudan giderir. Yorgunluğu gideren de dinlenmedir, ilişki aynıdır. Mutfak ve yatak ihtiyacın giderildiği yerdir, doktor ise yardım eden kişidir, bunların hiçbiri ihtiyacı kendi başına gidermez. Soğuk ile kış arasında giderme değil, durum ile mevsim ilişkisi vardır."},
    {"n":7,"b":"SOZ","z":4,"d":2,"s":"Planı hazırlarken herkesin görüşünü aldı, ancak son kararı kendisi verdi. cümlesinden çıkarılabilecek yargı hangisidir?","sec":["Kimsenin görüşünü dikkate almamıştır.","Karar ortak biçimde alınmıştır.","Görüş toplamış olsa da kararı tek başına vermiştir.","Planı hazırlarken kimseye danışmamıştır.","Toplanan görüşlerin tümü plana yansımıştır."],"ac":"Cümlenin ilk bölümü görüş toplandığını, ikinci bölümü kararın tek kişiye ait olduğunu söyler. İkisini birlikte veren tek seçenek budur. Kimseye danışmadı ya da karar ortak alındı demek cümlenin yalnız bir yarısını okumaktır. Görüşlerin plana yansıyıp yansımadığı ise cümlede belirtilmemiştir."},
    {"n":8,"b":"SOZ","z":5,"d":4,"s":"Bir yarışmaya katılan her öğrenci ya satranç ya da masa tenisi kulübündendir. Satranç kulübünden katılanların tümü dokuzuncu sınıftadır. Yarışmada onuncu sınıf öğrencileri de vardır. Buna göre kesinlikle doğru olan hangisidir?","sec":["Yarışmaya katılanların tümü dokuzuncu sınıftadır.","Masa tenisi kulübünden katılanların tümü onuncu sınıftadır.","Satranç kulübünden yarışmaya katılan yoktur.","Onuncu sınıftan katılanların bir bölümü satranç kulübündendir.","Masa tenisi kulübünden en az bir öğrenci yarışmaya katılmıştır."],"ac":"Satranç kulübünden katılanların tümü dokuzuncu sınıfta olduğuna göre onuncu sınıftan biri satranç kulübünden katılmış olamaz. Her katılımcı iki kulüpten birinde olduğuna göre yarışmadaki onuncu sınıf öğrencisi masa tenisi kulübündendir. Öyleyse masa tenisinden en az bir katılımcı bulunması kesindir. Masa tenisi katılımcılarının tümünün onuncu sınıf olması ise kesin değildir, dokuzuncu sınıftan da olabilirler."},
    {"n":9,"b":"SAY","z":2,"d":1,"s":"Bir sınıftaki öğrencilerin 12'si kız, 18'i erkektir. Kız öğrenci sayısının erkek öğrenci sayısına oranı kaçtır?","sec":["1/2","2/3","3/2","2/5","3/5"],"ac":"Oran, kız sayısının erkek sayısına bölümüdür: 12 / 18. Pay ve paydayı 6'ya bölersek 2/3 bulunur. Oranı 18/12 biçiminde kurmak 3/2 verir, bu ters çevirme hatasıdır. 12/30 ise kızların tüm sınıfa oranıdır, yani 2/5, soruda istenen bu değildir."},
    {"n":10,"b":"SAY","z":3,"d":3,"s":"3, 6, 11, 18, 27, ... biçiminde giden dizinin altıncı terimi kaçtır?","sec":["34","36","37","38","40"],"ac":"Ardışık terimler arasındaki farklar 3, 5, 7, 9 biçiminde ikişer artıyor. Sıradaki fark 9 + 2 = 11 olur. Son terime ekleyelim: 27 + 11 = 38. Farkın 9 olarak süreceğini düşünmek 36 gibi yanlış bir sonuç verir."},
    {"n":11,"b":"SAY","z":2,"d":0,"s":"240 sayfalık bir kitabın yüzde 35'i okunmuştur. Kaç sayfa okunmuştur?","sec":["84","96","120","144","156"],"ac":"Yüzde 35 için 240 x 35 / 100 işlemi yapılır. 240 x 35 = 8400 ve 8400 / 100 = 84 sayfa bulunur. Okunmayan sayfa sayısı 240 - 84 = 156'dır, bu değeri işaretlemek sık yapılan bir hatadır."},
    {"n":12,"b":"SAY","z":3,"d":2,"s":"Bir servis aracı 45 dakikada 36 kilometre yol almaktadır. Aynı hızla gittiğine göre 1 saatte kaç kilometre yol alır?","sec":["27","42","48","54","60"],"ac":"Araç bir dakikada 36 / 45 = 0,8 kilometre gider. Bir saat 60 dakika olduğuna göre 0,8 x 60 = 48 kilometre yol alır. İşlemi 36 x 45 / 60 biçiminde kurmak 27 verir, bu oranı ters kurma hatasıdır. Süredeki dakika sayısını doğrudan yola yazmak da 60 gibi yanlış bir sonuca götürür."},
    {"n":13,"b":"SAY","z":4,"d":4,"s":"Bir okulda dokuzuncu sınıf öğrencilerinin üçte biri fen kulübüne, dörtte biri müzik kulübüne yazılmıştır. Hiçbir öğrenci iki kulübe birden yazılmamıştır ve kulüp seçmeyen 25 öğrenci vardır. Dokuzuncu sınıfların toplam mevcudu kaçtır?","sec":["36","45","48","50","60"],"ac":"Kulübe yazılanlar mevcudun 1/3 + 1/4 = 7/12'sidir, geriye 5/12'si kalır. Bu 5/12'lik bölüm 25 öğrenciye eşit olduğuna göre mevcudun 1/12'si 5, tamamı 12 x 5 = 60'tır. Denetleyelim: 60'ın üçte biri 20, dörtte biri 15, toplam 35 eder ve 60 - 35 = 25 çıkar."},
    {"n":14,"b":"SAY","z":3,"d":1,"s":"Bir kantinde 3 poğaça ile 2 ayranın toplam tutarı 96 liradır. Bir poğaça 20 lira olduğuna göre bir ayran kaç liradır?","sec":["12","18","20","24","32"],"ac":"Üç poğaça 3 x 20 = 60 lira tutar. Ayranlara kalan tutar 96 - 60 = 36 liradır. İki ayran 36 lira ise bir ayran 36 / 2 = 18 liradır. Kalan tutarı ikiye değil üçe bölmek 12 gibi yanlış bir sonuç verir."},
    {"n":15,"b":"SAY","z":4,"d":3,"s":"Fiyatı 4000 lira olan bir bisiklete önce yüzde 10 zam yapılmış, sonra yeni fiyatı üzerinden yüzde 10 indirim uygulanmıştır. Bisikletin son fiyatı kaç liradır?","sec":["3600","3800","3900","3960","4000"],"ac":"Zam sonrası fiyat 4000 x 1,10 = 4400 lira olur. İndirim bu yeni fiyata uygulanır: 4400 x 0,90 = 3960 lira. Zam ile indirimin birbirini götürdüğünü düşünmek 4000 sonucunu verir, oysa indirim daha büyük bir tutar üzerinden hesaplandığı için son fiyat başlangıçtan düşüktür. Zammı hiç uygulamadan yalnız indirim yapmak ise 3600 verir."},
    {"n":16,"b":"SAY","z":5,"d":2,"s":"Bir işi Deniz tek başına 6 günde, Kaan tek başına 12 günde bitirmektedir. İkisi birlikte çalışırsa aynı iş kaç günde biter?","sec":["2","3","4","9","18"],"ac":"Deniz bir günde işin 1/6'sını, Kaan 1/12'sini bitirir. Birlikte bir günde 1/6 + 1/12 = 2/12 + 1/12 = 3/12 = 1/4'ünü bitirirler. İşin tamamı için 4 gün gerekir. Süreleri toplamak 18, ortalamalarını almak 9 verir, birlikte çalışmada süre ikisinin de tek başına süresinden kısa olmalıdır."},
    {"n":17,"b":"VER","z":2,"d":0,"tablo":{"baslik":"Okul kütüphanesinden aylara göre ödünç alınan kitap sayısı","basliklar":["Ay","Kitap sayısı"],"satirlar":[["Ekim","180"],["Kasım","240"],["Aralık","210"],["Ocak","150"]]},"s":"Tabloya göre en çok kitap ödünç alınan ay ile en az kitap ödünç alınan ay arasındaki fark kaç kitaptır?","sec":["90","150","210","240","390"],"ac":"En çok kitap Kasım ayında 240, en az kitap Ocak ayında 150 adettir. Fark 240 - 150 = 90 kitaptır. Yalnız en yüksek ya da en düşük değeri yazmak soruyu yanıtlamaz, iki sayıyı toplamak ise 390 gibi yanlış bir sonuç verir."},
    {"n":18,"b":"VER","z":3,"d":4,"tablo":{"baslik":"Kantinde iki hafta boyunca satılan ürün adedi","basliklar":["Ürün","1. hafta","2. hafta"],"satirlar":[["Ayran","200","250"],["Su","300","360"],["Süt","150","120"]]},"s":"Tabloya göre ayran satışındaki yüzde değişim nedir?","sec":["Yüzde 20 artış","Yüzde 20 azalış","Yüzde 25 azalış","Yüzde 50 artış","Yüzde 25 artış"],"ac":"Ayran satışı 200'den 250'ye çıkmış, artış 50 adettir. Yüzde değişimde artış ilk değere bölünür: 50 / 200 = 0,25, yani yüzde 25 artış. Artışı yeni değere bölmek (50 / 250) yüzde 20 verir, bu sık yapılan bir hatadır. Yüzde 20 artış su satırının, yüzde 20 azalış ise süt satırının değişimidir."},
    {"n":19,"b":"VER","z":2,"d":1,"tablo":{"baslik":"Üç şubenin deneme sınavı sonuçları","basliklar":["Şube","Mevcut","Ortalama puan"],"satirlar":[["9-A","20","72"],["9-B","25","68"],["9-C","30","70"]]},"s":"Tabloya göre aşağıdakilerden hangisi doğrudur?","sec":["En kalabalık şubenin ortalaması en yüksektir.","Mevcudu en az olan şubenin ortalaması en yüksektir.","Üç şubenin ortalama puanı birbirine eşittir.","9-B'nin ortalaması 9-C'ninkinden yüksektir.","Mevcut arttıkça ortalama puan da artmaktadır."],"ac":"Mevcudu en az şube 20 kişiyle 9-A'dır ve ortalaması 72 ile en yüksektir. En kalabalık şube olan 9-C'nin ortalaması 70'tir, bu da en yüksek değildir. 9-B'nin ortalaması 68, 9-C'ninki 70 olduğundan 9-B daha düşüktür. Mevcut 20'den 25'e çıkarken ortalama düşüyor, 25'ten 30'a çıkarken yükseliyor, bu nedenle düzenli bir artış yoktur."},
    {"n":20,"b":"VER","z":3,"d":3,"tablo":{"baslik":"Kitap bağışı kampanyasında günlere göre toplanan kitap","basliklar":["Gün","Toplanan kitap"],"satirlar":[["Pazartesi","24"],["Salı","31"],["Çarşamba","18"],["Perşembe","27"]]},"s":"Tabloya göre günlük ortalama kaç kitap toplanmıştır?","sec":["18","20","24","25","100"],"ac":"Dört günün toplamı 24 + 31 + 18 + 27 = 100 kitaptır. Ortalama için toplam, gün sayısına bölünür: 100 / 4 = 25. Toplamı beşe bölmek 20 verir, oysa tabloda dört gün vardır. Toplamın kendisini ortalama sanmak da 100 gibi yanlış bir sonuç doğurur."},
    {"n":21,"b":"VER","z":4,"d":2,"tablo":{"baslik":"Sınıf düzeylerine göre servis kullanan öğrenci sayısı","basliklar":["Sınıf düzeyi","Servis kullanan","Toplam öğrenci"],"satirlar":[["9","48","120"],["10","35","100"],["11","30","150"],["12","24","80"]]},"s":"Tabloya göre aşağıdakilerden hangisi söylenebilir?","sec":["Servis kullanma oranı en yüksek düzey 10. sınıftır.","Her düzeyde öğrencilerin yarısından çoğu servis kullanmaktadır.","Servis kullanma oranı en düşük düzey 11. sınıftır.","12. sınıfta servis kullanan sayısı en az olduğu için oranı da en düşüktür.","Okuldaki öğrencilerin yarısı servis kullanmaktadır."],"ac":"Her düzeyde oran, servis kullananın toplam öğrenciye bölümüdür: 48/120 = 0,40; 35/100 = 0,35; 30/150 = 0,20; 24/80 = 0,30. En düşük oran 0,20 ile 11. sınıftadır, en yüksek oran ise 9. sınıftadır. 12. sınıfta servis kullanan sayı 24 ile en az olsa da oranı 0,30'dur, sayı ile oranı karıştırmak yanlış sonuca götürür. Okul genelinde 137 öğrenci 450 öğrencinin yarısından azdır."},
    {"n":22,"b":"VER","z":3,"d":0,"tablo":{"baslik":"Kulüp seçiminde öğrencilerin tercihleri","basliklar":["Kulüp","Öğrenci sayısı"],"satirlar":[["Satranç","36"],["Müzik","48"],["Tiyatro","60"],["Spor","56"]]},"s":"Tabloya göre tiyatro kulübünü seçen öğrenciler tüm seçimlerin yüzde kaçıdır?","sec":["30","33","48","56","60"],"ac":"Tüm seçimlerin toplamı 36 + 48 + 60 + 56 = 200'dür. Tiyatroyu seçen 60 öğrencinin oranı 60 / 200 = 0,30, yani yüzde 30'dur. Öğrenci sayısını doğrudan yüzde olarak okumak yüzde 60 gibi yanlış bir sonuç verir. Toplama bir kulübü katmayı unutmak da (60 / 180) yüzde 33'e götürür."},
    {"n":23,"b":"VER","z":4,"d":3,"tablo":{"baslik":"İki kantinin dört günlük satış tutarı (lira)","basliklar":["Gün","A kantini","B kantini"],"satirlar":[["Pazartesi","1200","900"],["Salı","950","1150"],["Çarşamba","1100","1250"],["Perşembe","1050","1450"]]},"s":"Tabloya göre dört gün sonunda iki kantinin toplam satış tutarları arasındaki fark kaç liradır?","sec":["150","200","300","450","9050"],"ac":"A kantininin toplamı 1200 + 950 + 1100 + 1050 = 4300 liradır. B kantininin toplamı 900 + 1150 + 1250 + 1450 = 4750 liradır. Fark 4750 - 4300 = 450 liradır. Tek bir günün farkına bakmak 150, 200 ya da 300 verir, iki toplamı toplamak ise 9050 gibi anlamsız bir sonuç doğurur."},
    {"n":24,"b":"VER","z":5,"d":1,"tablo":{"baslik":"Yıllara göre okul gezisine katılım","basliklar":["Yıl","Katılan öğrenci","Okul mevcudu"],"satirlar":[["2023","120","600"],["2024","150","750"],["2025","160","1000"]]},"s":"Tabloya göre aşağıdakilerden hangisi söylenebilir?","sec":["Katılım oranı her yıl bir öncekine göre artmıştır.","2025 yılında katılan öğrenci sayısı en yüksek, katılım oranı en düşüktür.","2024 yılındaki katılım oranı 2023 yılındakinden yüksektir.","Okul mevcudu arttıkça katılım oranı da artmaktadır.","Üç yıl boyunca katılım oranı hiç değişmemiştir."],"ac":"Katılım oranı için katılan sayısı mevcuda bölünür: 120/600 = 0,20; 150/750 = 0,20; 160/1000 = 0,16. Katılan öğrenci sayısı 160 ile 2025'te en yüksektir, oran ise aynı yıl 0,16 ile en düşüktür. 2023 ile 2024 oranı eşit olduğundan her yıl arttığı söylenemez. Oran üçüncü yıl düştüğü için hiç değişmediği de söylenemez."},
    {"n":25,"b":"MAN","z":2,"s":"Bir okulda şu kural geçerlidir: Servis gecikirse ilk ders yirmi dakika geç başlar. Bugün ilk ders geç başlamadı. Buna göre kesin olarak ne söylenebilir?","sec":["Servis gecikmedi.","Servis gecikti ama ders yine de zamanında başladı.","İlk ders her gün zamanında başlar.","Servis gecikmese bile ders geç başlayabilir.","Bugün servis hiç gelmedi."],"d":0,"ac":"Kural, servis gecikmesini dersin geç başlamasına bağlar. Ders geç başlamadığına göre kuralın sonucu gerçekleşmemiştir. Sonuç gerçekleşmediyse koşul da gerçekleşmemiş olmalıdır, yani servis gecikmemiştir."},
    {"n":26,"b":"MAN","z":2,"s":"Bir okul kulübünün bütün üyeleri satranç turnuvasına katıldı. Turnuvaya katılan herkes kayıt formu doldurdu. Selin bu kulübün üyesi olduğuna göre kesin olan hangisidir?","sec":["Kayıt formu dolduran herkes kulüp üyesidir.","Selin turnuvaya katılmadı.","Selin kayıt formu doldurdu.","Selin turnuvada ilk üçe girdi.","Kulüp üyesi olmayan hiç kimse form doldurmamıştır."],"d":2,"ac":"Selin kulüp üyesi olduğundan turnuvaya katılanlar arasındadır. Turnuvaya katılan herkes form doldurduğuna göre Selin de doldurmuştur. Öteki seçenekler kuralı ters yönde okur, öncüller bunu gerektirmez."},
    {"n":27,"b":"MAN","z":3,"s":"Beş öğrenci bir koşuyu tamamlıyor ve hiçbiri aynı anda bitirmiyor. Berk birinci olmuştur. Ceren, Deniz'in hemen arkasından bitirmiştir. Ali, Elif'ten önce bitirmiştir. Elif sonuncu değildir. Buna göre üçüncü sırada kim bitirmiştir?","sec":["Ali","Berk","Ceren","Deniz","Elif"],"d":4,"ac":"Berk birinci olduğu için kalan dördü 2, 3, 4 ve 5. sıralara yerleşir. Deniz ile Ceren yan yana olduğundan bu ikili ancak 2-3, 3-4 ya da 4-5 sıralarına girer; ilk iki durumda Ali ile Elif'e kalan yerlerde Elif sonuncu olur, bu ise yasaktır. Geriye Deniz 4, Ceren 5 kalır; Ali 2, Elif 3 olur. Sıralama Berk, Ali, Elif, Deniz, Ceren olduğundan üçüncü Elif'tir."},
    {"n":28,"b":"MAN","z":4,"s":"Beş arkadaş sinemada yan yana beş koltuğa oturuyor, koltuklar soldan sağa 1'den 5'e numaralı. Naz 1. koltukta oturuyor. Pelin, Onur'un hemen solunda. Rüya, Mert'in hemen solunda. Mert 5. koltukta oturmuyor. Buna göre 4. koltukta kim oturuyor?","sec":["Mert","Pelin","Naz","Onur","Rüya"],"d":1,"ac":"Naz 1. koltukta olduğu için Rüya-Mert ve Pelin-Onur ikilileri 2-3 ile 4-5 koltuklarını paylaşmak zorundadır, çünkü 3-4 koltuklarını tutan bir ikili diğerine yan yana yer bırakmaz. İki olasılık kalır: Rüya-Mert 2-3 ve Pelin-Onur 4-5, ya da Pelin-Onur 2-3 ve Rüya-Mert 4-5. İkinci olasılıkta Mert 5. koltuğa düşer, bu ise yasaklanmıştır. Geriye Naz, Rüya, Mert, Pelin, Onur dizilişi kalır ve 4. koltukta Pelin oturur."},
    {"n":29,"b":"MAN","z":3,"s":"Bir lisede şu bilgi doğrudur: Kütüphane kartı olan her öğrenci okuma kulübüne üyedir. Yalnızca bu bilgiden kesin olarak çıkan sonuç hangisidir?","sec":["Okuma kulübüne üye olan her öğrencinin kütüphane kartı vardır.","Kütüphane kartı olmayan bir öğrenci okuma kulübüne üye değildir.","Okulda kütüphane kartı olmayan öğrenci yoktur.","Okuma kulübüne üye olmayan bir öğrencinin kütüphane kartı yoktur.","Kütüphane kartı olan bazı öğrenciler okuma kulübüne üye değildir."],"d":3,"ac":"Verilen önerme, kart sahibi olmanın kulüp üyeliğini gerektirdiğini söyler. Üye olmayan birinin kartı olsaydı bu kural çiğnenirdi, dolayısıyla üye olmayanın kartı yoktur. İlk iki seçenek kuralı ters çevirir, bu geçerli bir çıkarım değildir."},
    {"n":30,"b":"MAN","z":3,"s":"Bir sayı dizisi şöyle ilerliyor: 2, 5, 11, 23, 47, ... Dizinin kuralına göre bundan sonraki sayı kaçtır?","sec":["71","94","95","96","141"],"d":2,"ac":"Her sayı bir öncekinin iki katının bir fazlasıdır: 5 = 2 x 2 + 1, 11 = 5 x 2 + 1 ve dizi böyle sürer. Aynı kural 47 için 47 x 2 + 1 = 95 verir. Farklara bakan da aynı sonuca ulaşır, çünkü farklar 3, 6, 12, 24 gider ve sonraki fark 48 olur."},
    {"n":31,"b":"MAN","z":4,"s":"Dört arkadaşın deneme sınavı netleri karşılaştırılıyor ve hiçbiri eşit net yapmamıştır. Zeynep, Umut'tan çok net yapmıştır. Hakan, Umut'tan çok net yapmıştır. Zeynep, Hakan'dan çok net yapmıştır. İpek, Umut'tan az net yapmıştır. Netleri çoktan aza doğru sıralayan seçenek hangisidir?","sec":["Zeynep, Hakan, Umut, İpek","Hakan, Zeynep, Umut, İpek","Zeynep, Umut, Hakan, İpek","Zeynep, Hakan, İpek, Umut","İpek, Umut, Hakan, Zeynep"],"d":0,"ac":"Zeynep hem Umut'tan hem Hakan'dan çok net yaptığı için en üsttedir. Hakan Umut'tan çok yaptığından ikinci, Umut üçüncü olur. İpek Umut'tan da az yaptığına göre en alttadır, tek sıralama Zeynep, Hakan, Umut, İpek olur."},
    {"n":32,"b":"MAN","z":5,"s":"Bir sınıfta kaybolan kalemi üç öğrenciden biri almıştır. Ali \"Kalemi ben almadım\" diyor, Berk \"Kalemi Ali aldı\" diyor, Can \"Kalemi ben almadım\" diyor. Bu üç cümleden yalnızca biri doğruysa kalemi kim almıştır?","sec":["Ali","Berk","Can","Ali ile Berk birlikte","Verilen bilgiyle bulunamaz"],"d":2,"ac":"Kalemi Ali almış olsaydı Berk ile Can doğru söylemiş olurdu, bu iki doğru cümle demektir. Berk almış olsaydı Ali ile Can doğru söylerdi, yine iki doğru çıkar. Can almışsa yalnız Ali doğru söyler, Berk ile Can yanılır. Tek doğru koşulu ancak bu durumda sağlandığı için kalemi Can almıştır."},
    {"n":33,"b":"UZM","z":2,"s":"Kare bir kâğıt, dikey orta çizgisi boyunca ikiye katlanıyor ve sağ yarı sol yarının üstüne geliyor. Katlı kâğıdın üst bölümüne delgeçle tek bir delik açılıp kâğıt tamamen açılıyor. Açılan kâğıtta delikler nasıl görünür?","sec":["Üst bölümde tek bir delik bulunur.","Üst bölümde, dikey katlama çizgisine göre simetrik iki delik bulunur.","Alt bölümde, dikey katlama çizgisine göre simetrik iki delik bulunur.","Yatay orta çizgiye göre simetrik iki delik bulunur.","Kâğıdın dört köşesinde dört delik bulunur."],"d":1,"ac":"Tek katlama kâğıdı iki kat yapar, delgeç iki katı birden deldiği için açılınca iki delik çıkar. Katlama dikey çizgide yapıldığından bu çizgi bir simetri eksenidir. Delik üst bölümde açıldığı için iki delik de üst bölümde ve dikey çizgiye göre simetrik durur.","g":{"tur":"kagit-katlama","tarif":"Üç aşamalı çizim. Solda kare kâğıt, dikey orta çizgisi kesikli ve sağ yarıyı sola çeviren kıvrık bir ok. Ortada katlanmış hâl: karenin yarısı genişliğinde dikey bir dikdörtgen, dikdörtgenin üst yarısının merkezinde içi dolu küçük bir daire. Sağda açılmış kare, delik yerleri boş bırakılmış, seçenek çizimleri buraya yerleşecek.","secenek_tarifleri":["Açık karenin üst yarısında, dikey orta çizginin solunda tek bir delik.","Açık karenin üst yarısında, dikey orta çizgiden eşit uzaklıkta iki delik.","Açık karenin alt yarısında, dikey orta çizgiden eşit uzaklıkta iki delik.","Açık karede dikey orta çizgi üzerinde, biri üstte biri altta iki delik.","Açık karenin dört köşesine yakın dört delik."]}},
    {"n":34,"b":"UZM","z":3,"s":"Artı biçiminde bir küp açınımının dikey kolunda yukarıdan aşağıya daire, üçgen, yıldız ve boş yüz vardır. Üçgenli karenin solunda kare işareti, sağında yatay çizgi bulunur. Bu açınım katlandığında dairenin karşısındaki yüzde hangi şekil olur?","sec":["Kare işareti","Üçgen","Yatay çizgi","Yıldız","Boş yüz"],"d":3,"ac":"Açınımın dikey kolu dört kareden oluşur: daire, üçgen, yıldız, boş yüz. Dört karelik bir şeritte birinci ile üçüncü kare, ikinci ile dördüncü kare küp katlanınca karşılıklı yüzlere gelir. Daire birinci, yıldız üçüncü sırada olduğu için dairenin karşısında yıldız bulunur. Sağdaki ve soldaki kareler birbirinin karşısına geldiğinden kare işareti ile yatay çizgi dairenin karşısı olamaz.","g":{"tur":"kup-acinimi","tarif":"Artı biçiminde altı eş kare. Dikey kolda yukarıdan aşağıya dört kare: birincide içi dolu daire, ikincide yukarı bakan eşkenar üçgen, üçüncüde beş köşeli yıldız, dördüncü kare boş. İkinci karenin solundaki kareye küçük bir kare işareti, sağındaki kareye yatay bir çizgi. Şekiller kare merkezlerine ortalanır, döndürülmez.","secenek_tarifleri":["Küpün bir yüzünde küçük kare işareti.","Küpün bir yüzünde yukarı bakan üçgen.","Küpün bir yüzünde yatay çizgi.","Küpün bir yüzünde beş köşeli yıldız.","Küpün hiçbir şekil taşımayan boş yüzü."]}},
    {"n":35,"b":"UZM","z":2,"s":"Bir bayrak şekli çiziliyor: dikey duran bir direk ve direğin üst ucunun sağına takılı dikdörtgen bir kumaş. Bu şekil saat yönünde 90 derece döndürülüyor. Döndürmeden sonra şekil nasıl görünür?","sec":["Direk yatay ve sağa uzanır, kumaş direğin sağ ucunun altındadır.","Direk yatay ve sağa uzanır, kumaş direğin sağ ucunun üstündedir.","Direk yatay ve sola uzanır, kumaş direğin sol ucunun üstündedir.","Direk dikey kalır, kumaş üst ucun soluna geçer.","Direk yatay ve sola uzanır, kumaş direğin sol ucunun altındadır."],"d":0,"ac":"Saat yönünde 90 derecelik dönüşte yukarı bakan yön sağa döner, sağa bakan yön aşağı iner. Direğin üst ucu sağa gider ve direk yatay hâle gelir. Direğin sağındaki kumaş aynı dönüşle aşağı indiği için sağ ucun altına geçer. Dönüş ters yönde olsaydı direk sola uzanır, kumaş üstte kalırdı.","g":{"tur":"iki-boyutlu-dondurme","tarif":"Soruda tek şekil: aşağıdan yukarı uzanan ince dikey bir direk çizgisi ve direğin üst ucundan sağa doğru çıkan, direk boyunun üçte biri yüksekliğinde dolu dikdörtgen kumaş. Yanında saat yönünü gösteren 90 derecelik kıvrık ok.","secenek_tarifleri":["Yatay direk sağa uzanır, dikdörtgen kumaş sağ uçtan aşağı sarkar.","Yatay direk sağa uzanır, dikdörtgen kumaş sağ uçtan yukarı çıkar.","Yatay direk sola uzanır, dikdörtgen kumaş sol uçtan yukarı çıkar.","Dikey direk yerinde durur, dikdörtgen kumaş üst uçtan sola çıkar.","Yatay direk sola uzanır, dikdörtgen kumaş sol uçtan aşağı sarkar."]}},
    {"n":36,"b":"UZM","z":3,"s":"Dik kenarları 3 ve 4 birim olan iki eş dik üçgen, eşit uzunluktaki birer kenarı tam çakışacak biçimde birleştiriliyor. Aşağıdaki şekillerden hangisi bu yolla elde edilemez?","sec":["Kenarları 3 ve 4 birim olan bir dikdörtgen","Bir paralelkenar","Bir ikizkenar üçgen","Bir kare","Kenarları sırayla 3, 4, 4, 3 birim olan bir deltoid"],"d":3,"ac":"İki üçgenin toplam alanı 12 birim karedir, kare olsaydı kenarının karesi 12 olurdu ve bu uzunluk parçaların 3, 4, 5 birimlik kenarlarıyla elde edilemez. Hipotenüsler çakıştırılırsa 3 ile 4 birimlik dikdörtgen ya da deltoid oluşur. Dik kenarlar çakıştırılırsa paralelkenar veya tabanı 8, yan kenarları 5 birim olan ikizkenar üçgen çıkar. Geriye elde edilemeyen tek şekil olarak kare kalır.","g":{"tur":"parca-birlestirme","tarif":"Üstte iki eş dik üçgen yan yana: dik kenarları 3 ve 4 birim, hipotenüsü 5 birim, uzunluklar kenarlara yazılı. Soldaki üçgenin dik açısı sol altta, sağdaki aynı üçgenin 180 derece döndürülmüş hâli. Altta birleştirme sonuçları için beş seçenek kutusu, her birinde birleşme kenarı kesikli çizgiyle gösterilir.","secenek_tarifleri":["Kısa kenarı 3, uzun kenarı 4 birim olan dikdörtgen, köşegeni kesikli.","Eğik kenarlı paralelkenar, birleşme kenarı kesikli.","Tabanı 8 birim, yan kenarları 5 birim olan ikizkenar üçgen, orta dikmesi kesikli.","Dört kenarı eşit bir kare, köşegeni kesikli.","Kenarları sırayla 3, 4, 4, 3 birim olan uçurtma biçimli deltoid, uzun köşegeni kesikli."]}},
    {"n":37,"b":"UZM","z":3,"s":"Dikdörtgen bir kartın sol üst köşesinde içi dolu bir daire, sağ alt köşesinde bir üçgen vardır. Kart, sağ kenarına paralel duran dikey bir aynada yansıtılıyor. Aynadaki görüntüde şekiller nerede olur?","sec":["Daire sol üstte, üçgen sağ altta kalır.","Daire sağ üstte, üçgen sol alttadır.","Daire sol altta, üçgen sağ üsttedir.","Daire sağ altta, üçgen sol üsttedir.","Daire sağ üstte, üçgen sağ alttadır."],"d":1,"ac":"Dikey ayna sağ ile solu yer değiştirir, üst ile altı değiştirmez. Sol üstteki daire sağ üste, sağ alttaki üçgen sol alta geçer. Hem sağ solu hem üst altı değiştirmek 180 derece döndürmek olurdu, bu ayna görüntüsü değildir.","g":{"tur":"ayna-simetrisi","tarif":"Solda yatay duran dikdörtgen bir kart: sol üst köşesine yakın içi dolu daire, sağ alt köşesine yakın yukarı bakan küçük üçgen. Kartın hemen sağında, sağ kenarına paralel dikey kesikli ayna çizgisi. Ayna çizgisinin sağında aynı boyutta boş kart, seçenek çizimleri buraya yerleşecek.","secenek_tarifleri":["Kartın sol üstünde daire, sağ altında üçgen.","Kartın sağ üstünde daire, sol altında üçgen.","Kartın sol altında daire, sağ üstünde üçgen.","Kartın sağ altında daire, sol üstünde üçgen.","Kartın sağ üstünde daire, sağ altında üçgen."]}},
    {"n":38,"b":"UZM","z":4,"s":"Bir küpün ön yüzünde daire, üst yüzünde kare, sağ yüzünde üçgen, sol yüzünde yıldız, arka yüzünde çarpı, alt yüzünde çizgi vardır. Küp, üstten bakıldığında saat yönünde olacak biçimde dikey ekseni çevresinde 90 derece döndürülüyor. Dönüş bitince öne bakan yüzde hangi şekil vardır?","sec":["Daire","Kare","Yıldız","Çarpı","Üçgen"],"d":4,"ac":"Dikey eksen çevresindeki dönüşte üst ve alt yüzler yerinde kalır, dört yan yüz sırayla kayar. Üstten bakıldığında saat yönündeki dönüş sağ yüzü öne getirir. Sağ yüzde üçgen olduğu için dönüş sonunda önde üçgen görünür. Dönüş ters yönde olsaydı sol yüzdeki yıldız, 180 derece olsaydı arkadaki çarpı öne gelirdi.","g":{"tur":"uc-boyutlu-dondurme","tarif":"Solda üç yüzü görünen bir küp çizimi: öne bakan yüzde içi dolu daire, üst yüzde kare işareti, sağ yüzde yukarı bakan üçgen. Küpün üstünde dikey ekseni gösteren kesikli doğru ve bu eksen çevresinde saat yönünü gösteren 90 derecelik ok. Sağda dönmüş küpün boş hâli, ön yüzü işaretsiz.","secenek_tarifleri":["Dönmüş küpün ön yüzünde içi dolu daire.","Dönmüş küpün ön yüzünde kare işareti.","Dönmüş küpün ön yüzünde beş köşeli yıldız.","Dönmüş küpün ön yüzünde çarpı işareti.","Dönmüş küpün ön yüzünde yukarı bakan üçgen."]}},
    {"n":39,"b":"UZM","z":4,"s":"Kare bir kâğıt önce yatay orta çizgisi boyunca, sonra dikey orta çizgisi boyunca katlanıyor. Oluşan küçük karenin tam ortasından delgeçle tek bir delik açılıyor ve kâğıt tamamen açılıyor. Açılan kâğıtta delikler nasıl görünür?","sec":["Dikey orta çizgiye göre simetrik iki delik bulunur.","Aynı yatay çizgi üzerinde sıralanmış dört delik bulunur.","Her çeyrekte bir tane olmak üzere, iki orta çizgiye göre de simetrik dört delik bulunur.","Bir üçgenin köşelerinde üç delik bulunur.","Kenarlara yakın sekiz delik bulunur."],"d":2,"ac":"İki katlama kâğıdı dört kat hâline getirir ve delgeç dört katı birden deler, bu yüzden açılınca dört delik çıkar. Katlama çizgilerinin ikisi de birer simetri eksenidir. Delik küçük karenin tam ortasında açıldığı için dört delik hem yatay hem dikey orta çizgiye göre simetrik durur, yani her çeyreğin merkezine bir tane düşer.","g":{"tur":"kagit-katlama","tarif":"Dört aşamalı çizim. Birinci: kare kâğıt, yatay orta çizgisi kesikli, alt yarıyı yukarı çeviren ok. İkinci: yatay dikdörtgen, dikey orta çizgisi kesikli, sağ yarıyı sola çeviren ok. Üçüncü: kenarı kare kâğıdın yarısı kadar olan küçük kare, tam merkezinde içi dolu daire. Dördüncü: açılmış kare, iki orta çizgisi kesikli, delik yerleri boş.","secenek_tarifleri":["Açık karede dikey orta çizgiden eşit uzaklıkta, aynı yükseklikte iki delik.","Açık karede yatay orta çizgi üzerinde eşit aralıklı dört delik.","Açık karenin dört çeyreğinin her birinin merkezinde birer delik, toplam dört delik.","Açık karede bir üçgenin köşelerinde üç delik.","Açık karede kenarlara yakın, çevreye dağılmış sekiz delik."]}},
    {"n":40,"b":"UZM","z":5,"s":"Bir küp açınımında dört kare soldan sağa şerit hâlinde dizilidir ve bunlarda sırayla daire, üçgen, çarpı ile boş yüz bulunur. Şeridin birinci karesinin üstüne kare işaretli bir kare, üçüncü karesinin altına yıldızlı bir kare eklenmiştir. Bu açınım katlandığında aşağıdaki şekil üçlülerinden hangisi küpün aynı köşesinde buluşan üç yüzde bulunur?","sec":["Daire, çarpı ve kare işareti","Üçgen, boş yüz ve yıldız","Kare işareti, yıldız ve daire","Çarpı, boş yüz ve daire","Daire, üçgen ve kare işareti"],"d":4,"ac":"Dört karelik şerit küpün yan yüzlerini oluşturur, bu yüzden daire ile çarpı, üçgen ile boş yüz karşılıklı yüzlere gelir. Şeridin üstüne ve altına eklenen kareler küpün üst ve alt yüzü olduğundan kare işareti ile yıldız da karşılıklıdır. Bir köşede buluşan üç yüzün hiçbir ikisi karşılıklı olamaz. Öteki seçeneklerin her birinde karşılıklı bir çift bulunduğu için koşulu yalnızca daire, üçgen ve kare işareti üçlüsü sağlar.","g":{"tur":"kup-acinimi","tarif":"Altı eş kareden oluşan açınım. Ortada yatay şerit hâlinde dört kare, soldan sağa: içi dolu daire, yukarı bakan üçgen, çarpı işareti, boş kare. Şeridin birinci karesinin tam üstüne kare işaretli bir kare, üçüncü karesinin tam altına beş köşeli yıldızlı bir kare eklenir. Şekiller kare merkezlerine ortalanır, döndürülmez.","secenek_tarifleri":["Küpün bir köşesinde buluşan üç yüzde daire, çarpı ve kare işareti.","Küpün bir köşesinde buluşan üç yüzde üçgen, boş yüz ve yıldız.","Küpün bir köşesinde buluşan üç yüzde kare işareti, yıldız ve daire.","Küpün bir köşesinde buluşan üç yüzde çarpı, boş yüz ve daire.","Küpün bir köşesinde buluşan üç yüzde daire, üçgen ve kare işareti."]}}
  ]
};
